from statistics import mean


attacks = []

b = (0, 1, 1, 1, 2, 2)
u = (1, 1, 2, 2, 2, 3)
o = (1, 2, 2, 3, 3, 4)
d = (0, 0, 0, 1, 1, 1)
means = {
    b: mean(b),
    u: mean(u),
    o: mean(o)
}


class Attack:
    def __init__(self, name, attackNumber, damage=[[]], damageMod=0, magic=False, bleed=False, poison=False, ignoreArmor=False, damageBonus=None) -> None:
        attacks.append(self)
        self.name = name
        self.attackNumber = attackNumber
        self.damage = damage
        self.damageMod = damageMod
        self.magic = magic
        self.bleed = bleed
        self.poison = poison
        self.ignoreArmor = ignoreArmor
        self.damageBonus = damageBonus
        self.expectedDamage = {
            -1: 0,
            0: 0,
            1: 0,
            2: 0,
            3: 0
        }
        for x in range(4):
            for attack in self.damage:
                for die in attack:
                    self.expectedDamage[x] += means[die]
                self.expectedDamage[x] = self.expectedDamage[x] + self.damageMod - x
            self.expectedDamage[x] = max([0, self.expectedDamage[x] + (1 if poison else 0)])

Attack(name="Abyss Greatsword", attackNumber=1, damage=[[b,b,b]])
Attack(name="Abyss Greatsword", attackNumber=2, damage=[[u,u,u]])
Attack(name="Aged Smelter Sword", attackNumber=1, damage=[[b,b,b,u]], magic=True)
Attack(name="Aged Smelter Sword", attackNumber=2, damage=[[u,o,o]], magic=True)
Attack(name="Alonne Greatbow", attackNumber=1, damage=[[b,b,b]])
Attack(name="Alonne Greatbow", attackNumber=2, damage=[[b,b,u]])
Attack(name="Avelyn", attackNumber=1, damage=[[u],[u],[u]])
Attack(name="Avelyn", attackNumber=2, damage=[[o],[o],[o]])
Attack(name="Balder Side Sword", attackNumber=1, damage=[[u,u]])
Attack(name="Balder Side Sword", attackNumber=2, damage=[[o,o]])
Attack(name="Bandit Knife", attackNumber=1, damage=[[b]])
Attack(name="Bandit Knife", attackNumber=2, damage=[[b,b]])
Attack(name="Battle Axe", attackNumber=1, damage=[[b,b]])
Attack(name="Battle Axe", attackNumber=2, damage=[[b,b]])
Attack(name="Bewitched Alonne Sword", attackNumber=1, damage=[[b,b]])
Attack(name="Bewitched Alonne Sword", attackNumber=2, damage=[[b,b,u]])
Attack(name="Bewitched Alonne Sword", attackNumber=3, damage=[[b,b,u,u]])
Attack(name="Black Bow of Pharis", attackNumber=1, damage=[[u]])
Attack(name="Black Bow of Pharis", attackNumber=2, damage=[[b,u]])
Attack(name="Black Bow of Pharis", attackNumber=3, damage=[[b,u]])
Attack(name="Black Firebombs", attackNumber=1, damage=[[u,u]], magic=True)
Attack(name="Black Knight Greataxe", attackNumber=1, damage=[[u,u]])
Attack(name="Black Knight Greataxe", attackNumber=2, damage=[[u,u]])
Attack(name="Black Knight Greataxe", attackNumber=3, damage=[[u,u]])
Attack(name="Black Knight Shield (Deprived)", attackNumber=1, damage=[[u]])
Attack(name="Black Knight Shield (Deprived)", attackNumber=2, damage=[[o]])
Attack(name="Black Knight Shield", attackNumber=1, damage=[[b,u]])
Attack(name="Black Knight Halberd", attackNumber=1, damage=[[b,b,b]])
Attack(name="Black Knight Halberd", attackNumber=2, damage=[[b,b,u]])
Attack(name="Black Knight Sword", attackNumber=1, damage=[[b,b]])
Attack(name="Black Knight Sword", attackNumber=2, damage=[[u,u,b]])
Attack(name="Blacksteel Katana", attackNumber=1, damage=[[b,b]])
Attack(name="Blacksteel Katana", attackNumber=2, damage=[[b,b,b]])
Attack(name="Blinding Bolt", attackNumber=1, damage=[[u],[u],[u],[u],[u]], magic=True)
Attack(name="Bloodshield", attackNumber=1, damage=[[b,b]])
Attack(name="Bonewheel Shield", attackNumber=1, damage=[[b,b]])
Attack(name="Bonewheel Shield", attackNumber=2, damage=[[b,b],[b,b],[b,b],[b,b]])
Attack(name="Brigand Axe", attackNumber=1, damage=[[b,b]])
Attack(name="Brigand Axe", attackNumber=2, damage=[[b,u]])
Attack(name="Broadsword", attackNumber=1, damage=[[b,b]])
Attack(name="Broadsword", attackNumber=2, damage=[[b,u]])
Attack(name="Broadsword", attackNumber=3, damage=[[u,u]])
Attack(name="Broken Straight Sword", attackNumber=1, damage=[[b,b,b]], damageMod=-2)
Attack(name="Broken Straight Sword", attackNumber=2, damage=[[u,u,u]], damageMod=-2)
Attack(name="Butcher Knife", attackNumber=1, damage=[[b,b]])
Attack(name="Butcher Knife", attackNumber=2, damage=[[u,u]])
Attack(name="Caestus", attackNumber=1, damage=[[b, b]])
Attack(name="Carthus Curved Greatsword", attackNumber=1, damage=[[b,b]], bleed=True)
Attack(name="Carthus Curved Greatsword", attackNumber=2, damage=[[b,b,b]], bleed=True)
Attack(name="Carthus Curved Sword", attackNumber=1, damage=[[u,u]], damageMod=-1)
Attack(name="Carthus Curved Sword", attackNumber=2, damage=[[u,u,u]], damageMod=-1)
Attack(name="Chariot Lance", attackNumber=1, damage=[[o]], bleed=True)
Attack(name="Chariot Lance", attackNumber=2, damage=[[u,o]], bleed=True)
Attack(name="Claws", attackNumber=1, damage=[[b,b],[b,b]])
Attack(name="Claws", attackNumber=2, damage=[[u,u],[u,u]])
Attack(name="Claymore", attackNumber=1, damage=[[u,u]], damageMod=1)
Attack(name="Claymore", attackNumber=2, damage=[[o,o]], damageMod=1)
Attack(name="Cleric's Candlestick", attackNumber=1, damage=[[b,u]], magic=True)
Attack(name="Cleric's Candlestick", attackNumber=2, damage=[[b,b,u]], magic=True)
Attack(name="Club", attackNumber=1, damage=[[b]])
Attack(name="Club", attackNumber=2, damage=[[b,b]])
Attack(name="Composite Bow", attackNumber=1, damage=[[b,b]], damageMod=-1)
Attack(name="Composite Bow", attackNumber=2, damage=[[b,b,b]], damageMod=-1)
Attack(name="Crescent Axe", attackNumber=1, damage=[[u]])
Attack(name="Crescent Axe", attackNumber=2, damage=[[u,u]], damageMod=1)
Attack(name="Crescent Moon Sword", attackNumber=1, damage=[[u]], magic=True)
Attack(name="Crescent Moon Sword", attackNumber=2, damage=[[u]], magic=True)
Attack(name="Crystal Hail", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Crystal Hail", attackNumber=2, damage=[[b,b]], magic=True)
Attack(name="Crystal Shield", attackNumber=1, damage=[[b,b,b]])
Attack(name="Crystal Straight Sword", attackNumber=1, damage=[[u]], damageMod=1)
Attack(name="Crystal Straight Sword", attackNumber=2, damage=[[b,u]], damageMod=1)
Attack(name="Cursed Greatsword of Artorias", attackNumber=1, damage=[[u,b]])
Attack(name="Cursed Greatsword of Artorias", attackNumber=2, damage=[[u,o]])
Attack(name="Dancer's Enchanted Swords", attackNumber=1, damage=[[u], [u]], magic=True)
Attack(name="Dancer's Enchanted Swords", attackNumber=2, damage=[[b,u], [b,u]], magic=True)
Attack(name="Dark Silver Tracer", attackNumber=1, damage=[[u,u]], damageMod=-1)
Attack(name="Dark Silver Tracer", attackNumber=2, damage=[[u,u]], damageMod=-1, poison=True)
Attack(name="Dark Sword", attackNumber=1, damage=[[u]])
Attack(name="Dark Sword", attackNumber=2, damage=[[u,u]])
Attack(name="Dark Sword", attackNumber=3, damage=[[o,o]])
Attack(name="Demon's Great Hammer", attackNumber=1, damage=[[u,u]])
Attack(name="Demon's Great Hammer", attackNumber=2, damage=[[o,o]])
Attack(name="Dragon King Greataxe", attackNumber=1, damage=[[o,o]])
Attack(name="Dragon King Greataxe", attackNumber=2, damage=[[o]], magic=True)
Attack(name="Dragon Tooth", attackNumber=1, damage=[[u,o,o]])
Attack(name="Dragon Tooth", attackNumber=2, damage=[[u,o,o]])
Attack(name="Dragonrider Bow", attackNumber=1, damage=[[o]], ignoreArmor=True)
Attack(name="Dragonrider Bow", attackNumber=2, damage=[[o]])
Attack(name="Dragonslayer Greatbow", attackNumber=1, damage=[[u,u]])
Attack(name="Dragonslayer Greatbow", attackNumber=2, damage=[[u,o]])
Attack(name="Dragonslayer Spear", attackNumber=1, damage=[[b,u]], magic=True)
Attack(name="Dragonslayer Spear", attackNumber=2, damage=[[b,u,u]], magic=True)
Attack(name="Dragonslayer Spear", attackNumber=3, damage=[[u,u]], magic=True)
Attack(name="Dragonslayer's Axe", attackNumber=1, damage=[[o]], magic=True)
Attack(name="Dragonslayer's Axe", attackNumber=2, damage=[[u,o]], magic=True)
Attack(name="Drake Sword", attackNumber=1, damage=[[u,u]])
Attack(name="Drake Sword", attackNumber=2, damage=[[o,o]])
Attack(name="Drake Sword", attackNumber=3, damage=[[u,u]])
Attack(name="Drakewing Ultra Greatsword", attackNumber=1, damage=[[u,o]])
Attack(name="Drakewing Ultra Greatsword", attackNumber=2, damage=[[o,o]])
Attack(name="Drang Hammers", attackNumber=1, damage=[[u,u]], damageMod=1, magic=True)
Attack(name="Drang Hammers", attackNumber=2, damage=[[u,u], [u,u]], magic=True)
Attack(name="Drang Hammers", attackNumber=3, damage=[[u,u], [u,u]], damageMod=1, magic=True)
Attack(name="Dung Pie", attackNumber=1, poison=True)
Attack(name="Estoc", attackNumber=1, damage=[[b,b]], damageMod=-1)
Attack(name="Estoc", attackNumber=2, damage=[[b,b,b]], damageMod=-1)
Attack(name="Exile Greatsword", attackNumber=1, damage=[[u,b]])
Attack(name="Exile Greatsword", attackNumber=2, damage=[[u,b]])
Attack(name="Exile Greatsword", attackNumber=3, damage=[[u,o]])
Attack(name="Falchion", attackNumber=1, damage=[[u,u]])
Attack(name="Falchion", attackNumber=2, damage=[[o,o]])
Attack(name="Fire Surge", attackNumber=1, damage=[[u]], magic=True)
Attack(name="Fire Surge", attackNumber=2, damage=[[u,u]], magic=True)
Attack(name="Fire Whip", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Fire Whip", attackNumber=2, damage=[[o,o]], magic=True)
Attack(name="Fireball", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Fireball", attackNumber=2, damage=[[o,o]], magic=True)
Attack(name="Firebombs", attackNumber=1, damage=[[b,b,b]], magic=True)
Attack(name="Flamberge", attackNumber=1, damage=[[o]], bleed=True)
Attack(name="Flamberge", attackNumber=2, damage=[[u,u]], bleed=True)
Attack(name="Four Kings Sword", attackNumber=1, damage=[[o]])
Attack(name="Four Kings Sword", attackNumber=2, damage=[[u,u]], magic=True)
Attack(name="Four-Pronged Plow", attackNumber=1, damage=[[u]])
Attack(name="Four-Pronged Plow", attackNumber=2, damage=[[u,u]])
Attack(name="Fume Ultra Greatsword", attackNumber=1, damage=[[u,o]])
Attack(name="Fume Ultra Greatsword", attackNumber=2, damage=[[u,u,o]])
Attack(name="Fume Ultra Greatsword", attackNumber=3, damage=[[u,o]])
Attack(name="Gargoyle Tail Axe", attackNumber=1, damage=[[u,u]])
Attack(name="Gargoyle Tail Axe", attackNumber=2, damage=[[u,u,u]])
Attack(name="Gargoyle's Halberd", attackNumber=1, damage=[[o]])
Attack(name="Gargoyle's Halberd", attackNumber=2, damage=[[o,o]])
Attack(name="Giant Stone Axe", attackNumber=1, damage=[[b,u]])
Attack(name="Giant Stone Axe", attackNumber=2, damage=[[u,o]])
Attack(name="Giant's Halberd", attackNumber=1, damage=[[b,u]])
Attack(name="Giant's Halberd", attackNumber=2, damage=[[b,o]])
Attack(name="Gold Tracer", attackNumber=1, damage=[[o,o]], damageMod=-1)
Attack(name="Gold Tracer", attackNumber=2, damage=[[o,o]], damageMod=-1, bleed=True)
Attack(name="Golden Ritual Spear", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Golden Ritual Spear", attackNumber=2, damage=[[u,u]], magic=True)
Attack(name="Golden Ritual Spear", attackNumber=3, damage=[[u,u]], magic=True)
Attack(name="Golden Wing Crest Shield", attackNumber=1, damage=[[b]])
Attack(name="Gotthard Twinswords", attackNumber=1, damage=[[b,b], [b,b]])
Attack(name="Gotthard Twinswords", attackNumber=2, damage=[[u,u], [u,u]])
Attack(name="Gotthard Twinswords", attackNumber=3, damage=[[u,u]])
Attack(name="Gravelord Sword", attackNumber=1, damage=[[b,u]], poison=True)
Attack(name="Gravelord Sword", attackNumber=2, damage=[[b,o]], poison=True)
Attack(name="Gravelord Sword Dance", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Gravelord Sword Dance", attackNumber=2, damage=[[u,u]], magic=True)
Attack(name="Greataxe", attackNumber=1, damage=[[u,u]])
Attack(name="Greataxe", attackNumber=2, damage=[[o,o]])
Attack(name="Greataxe", attackNumber=3, damage=[[u,u]])
Attack(name="Great Chaos Fireball", attackNumber=1, damage=[[o]], magic=True)
Attack(name="Great Chaos Fireball", attackNumber=2, damage=[[u,u,u]], magic=True)
Attack(name="Great Club", attackNumber=1, damage=[[o]])
Attack(name="Great Club", attackNumber=2, damage=[[o,o]])
Attack(name="Great Combustion", attackNumber=1, damage=[[u]], magic=True)
Attack(name="Great Combustion", attackNumber=2, damage=[[o]], magic=True)
Attack(name="Great Mace", attackNumber=1, damage=[[u]], damageMod=1)
Attack(name="Great Mace", attackNumber=2, damage=[[u,u]], damageMod=1)
Attack(name="Great Machete", attackNumber=1, damage=[[u,u,u]])
Attack(name="Great Machete", attackNumber=2, damage=[[b,b,o,o]])
Attack(name="Great Machete", attackNumber=3, damage=[[u,u,u]])
Attack(name="Great Scythe", attackNumber=1, damage=[[b,b,b]], damageMod=-1)
Attack(name="Great Scythe", attackNumber=2, damage=[[o,o]], damageMod=-1)
Attack(name="Great Stone Axe", attackNumber=1, damage=[[u,b]])
Attack(name="Great Stone Axe", attackNumber=2, damage=[[u,o]])
Attack(name="Great Wooden Hammer", attackNumber=1, damage=[[b,b,b]])
Attack(name="Great Wooden Hammer", attackNumber=2, damage=[[b,b,b]])
Attack(name="Greatsword", attackNumber=1, damage=[[b,u]])
Attack(name="Greatsword", attackNumber=2, damage=[[b,o]])
Attack(name="Greatsword of Artorias", attackNumber=1, damage=[[u,b]], magic=True)
Attack(name="Greatsword of Artorias", attackNumber=2, damage=[[u,o]], magic=True)
Attack(name="Halberd", attackNumber=1, damage=[[u]], damageMod=1)
Attack(name="Halberd", attackNumber=2, damage=[[u,u]], damageMod=1)
Attack(name="Hand Axe", attackNumber=1, damage=[[b]])
Attack(name="Hand Axe", attackNumber=2, damage=[[b,b]])
Attack(name="Hollow Soldier Shield", attackNumber=1, damage=[[b,b]], damageBonus="hollow")
Attack(name="Homing Crystal Soulmass", attackNumber=1, damage=[[o],[o],[o],[o],[o]], magic=True)
Attack(name="Immolation Tinder", attackNumber=1, damage=[[u]], magic=True)
Attack(name="Immolation Tinder", attackNumber=2, damage=[[b,b]], magic=True)
Attack(name="Immolation Tinder", attackNumber=3, damage=[[b,b]], magic=True)
Attack(name="Irithyll Rapier", attackNumber=1, damage=[[b,b]])
Attack(name="Irithyll Rapier", attackNumber=2, damage=[[b,u]])
Attack(name="Irithyll Straight Sword", attackNumber=1, damage=[[b,b]], damageMod=1)
Attack(name="Irithyll Straight Sword", attackNumber=2, damage=[[b,b,u]])
Attack(name="Iron King Hammer", attackNumber=1, damage=[[o]], magic=True)
Attack(name="Iron King Hammer", attackNumber=2, damage=[[b,u],[b,u]])
Attack(name="Lifehunt Scythe", attackNumber=1, damage=[[u,u]], damageMod=-1, bleed=True)
Attack(name="Lifehunt Scythe", attackNumber=2, damage=[[o,o]], damageMod=-1, bleed=True)
Attack(name="Long Sword", attackNumber=1, damage=[[u]])
Attack(name="Long Sword", attackNumber=2, damage=[[b,u]])
Attack(name="Longbow", attackNumber=1, damage=[[b,b]])
Attack(name="Longbow", attackNumber=2, damage=[[b,b,b]])
Attack(name="Lothric Knight Greatsword", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Lothric Knight Greatsword", attackNumber=2, damage=[[b,b,b]], magic=True)
Attack(name="Lothric's Holy Sword", attackNumber=1, damage=[[u]], magic=True)
Attack(name="Lothric's Holy Sword", attackNumber=2, damage=[[b,u]], magic=True)
Attack(name="Lucerne", attackNumber=1, damage=[[b,b,u]], damageMod=-1)
Attack(name="Lucerne", attackNumber=2, damage=[[b,b,b,u]], damageMod=-1)
Attack(name="Mace", attackNumber=1, damage=[[u]])
Attack(name="Mace", attackNumber=2, damage=[[b,b]])
Attack(name="Mail Breaker", attackNumber=1, damage=[[b]])
Attack(name="Mail Breaker", attackNumber=2, damage=[[u]])
Attack(name="Man Serpent Hatchet", attackNumber=1, damage=[[b,u]])
Attack(name="Man Serpent Hatchet", attackNumber=2, damage=[[b,u]], ignoreArmor=True)
Attack(name="Mannikin Claws", attackNumber=1, damage=[[b,b], [b,b]])
Attack(name="Mannikin Claws", attackNumber=2, damage=[[u,u], [u,u]])
Attack(name="Manus Catalyst", attackNumber=1, damage=[[u,u]])
Attack(name="Manus Catalyst", attackNumber=2, damage=[[o,o]])
Attack(name="Melinda's Greataxe", attackNumber=1, damage=[[o,o]])
Attack(name="Melinda's Greataxe", attackNumber=2, damage=[[o,o]])
Attack(name="Moonlight Greatsword", attackNumber=1, damage=[[b,u]], magic=True)
Attack(name="Moonlight Greatsword", attackNumber=2, damage=[[u,u,u]], magic=True)
Attack(name="Moonlight Greatsword", attackNumber=3, damage=[[u,u,u]], magic=True)
Attack(name="Morion Blade", attackNumber=1, damage=[[b]], bleed=True)
Attack(name="Morion Blade", attackNumber=2, damage=[[b,b]], bleed=True)
Attack(name="Morne's Great Hammer", attackNumber=1, damage=[[u,u]])
Attack(name="Morne's Great Hammer", attackNumber=2, damage=[[u,o]])
Attack(name="Morne's Great Hammer", attackNumber=3, damage=[[o,o]])
Attack(name="Morning Star", attackNumber=1, damage=[[u]])
Attack(name="Morning Star", attackNumber=2, damage=[[u,u]])
Attack(name="Murakamo", attackNumber=1, damage=[[b]])
Attack(name="Murakamo", attackNumber=2, damage=[[b,b,b]])
Attack(name="Notched Whip", attackNumber=1, damage=[[u]], bleed=True)
Attack(name="Notched Whip", attackNumber=2, damage=[[o]], bleed=True)
Attack(name="Obsidian Greatsword", attackNumber=1, damage=[[o,o]])
Attack(name="Obsidian Greatsword", attackNumber=2, damage=[[u,u]], magic=True)
Attack(name="Old Dragonslayer Spear", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Old Dragonslayer Spear", attackNumber=2, damage=[[b,b,b]], magic=True)
Attack(name="Old Dragonslayer Spear", attackNumber=3, damage=[[b,b]], magic=True)
Attack(name="Onikiri and Ubadachi", attackNumber=1, damage=[[u], [u]])
Attack(name="Onikiri and Ubadachi", attackNumber=2, damage=[[u,u], [u,u]])
Attack(name="Onikiri and Ubadachi", attackNumber=3, damage=[[o,o]])
Attack(name="Painting Guardian's Curved Sword", attackNumber=1, damage=[[b,b]], bleed=True)
Attack(name="Painting Guardian's Curved Sword", attackNumber=2, damage=[[b,b,b]], bleed=True)
Attack(name="Parrying Dagger", attackNumber=1, damage=[[b,b]], damageMod=-1)
Attack(name="Parrying Dagger", attackNumber=2, damage=[[b,b]])
Attack(name="Partizan", attackNumber=1, damage=[[u,u]])
Attack(name="Partizan", attackNumber=2, damage=[[u,u,o]])
Attack(name="Pierce Shield", attackNumber=1, damage=[[b,b]])
Attack(name="Pike", attackNumber=1, damage=[[b]], damageMod=1)
Attack(name="Pike", attackNumber=2, damage=[[b,b]], damageMod=1)
Attack(name="Pike", attackNumber=3, damage=[[b,b,b]], damageMod=1)
Attack(name="Poison Mist", attackNumber=1, poison=True)
Attack(name="Poison Mist", attackNumber=2, poison=True)
Attack(name="Poison Throwing Knives", attackNumber=1, damage=[[b,b]], poison=True)
Attack(name="Porcine Shield", attackNumber=1, damage=[[u]])
Attack(name="Priscilla's Dagger", attackNumber=1, damage=[[]], bleed=True)
Attack(name="Priscilla's Dagger", attackNumber=2, damage=[[o]], bleed=True)
Attack(name="Pursuer's Ultra Greatsword", attackNumber=1, damage=[[u,u]])
Attack(name="Pursuer's Ultra Greatsword", attackNumber=2, damage=[[u,u,o]])
Attack(name="Pursuers", attackNumber=1, damage=[[b,b],[b,b],[b,b],[b,b],[b,b]], magic=True)
Attack(name="Pyromancy Flame", attackNumber=1, damage=[[b]], magic=True)
Attack(name="Pyromancy Flame", attackNumber=2, damage=[[b,b]], magic=True)
Attack(name="Rapier", attackNumber=1, damage=[[b]], damageMod=1)
Attack(name="Rapier", attackNumber=2, damage=[[u,u]])
Attack(name="Reinforced Club", attackNumber=1, damage=[[u]])
Attack(name="Reinforced Club", attackNumber=2, damage=[[u,u]])
Attack(name="Rotten Ghru Dagger", attackNumber=1, damage=[[b,b]], damageMod=-1, poison=True)
Attack(name="Rotten Ghru Dagger", attackNumber=2, damage=[[b,b,b]], damageMod=-1, poison=True)
Attack(name="Rotten Ghru Spear", attackNumber=1, damage=[[b,b]], damageMod=-1, poison=True)
Attack(name="Rotten Ghru Spear", attackNumber=2, damage=[[b,b]], poison=True)
Attack(name="Royal Dirk", attackNumber=1, damage=[[u]])
Attack(name="Royal Dirk", attackNumber=2, damage=[[u,u]])
Attack(name="Saint Bident", attackNumber=1, damage=[[u,u]])
Attack(name="Saint Bident", attackNumber=2, damage=[[b,u,u]])
Attack(name="Santier's Spear", attackNumber=1, damage=[[u,u]], damageMod=1)
Attack(name="Santier's Spear", attackNumber=2, damage=[[u,u]])
Attack(name="Santier's Spear", attackNumber=3, damage=[[u,u,u]])
Attack(name="Sellsword Twinblades", attackNumber=1, damage=[[b], [b]])
Attack(name="Sellsword Twinblades", attackNumber=2, damage=[[b,b], [b,b]])
Attack(name="Scimitar", attackNumber=1, damage=[[b,b]])
Attack(name="Scimitar", attackNumber=2, damage=[[o,o]], damageMod=-1)
Attack(name="Shield Crossbow", attackNumber=1, damage=[[b,b]])
Attack(name="Shield Crossbow", attackNumber=2, damage=[[u,u]])
Attack(name="Shortbow", attackNumber=1, damage=[[u]])
Attack(name="Shortbow", attackNumber=2, damage=[[b,b]])
Attack(name="Shortsword", attackNumber=1, damage=[[b,b]])
Attack(name="Shortsword", attackNumber=2, damage=[[b,b,b]])
Attack(name="Shotel", attackNumber=1, damage=[[b]])
Attack(name="Shotel", attackNumber=2, damage=[[b]], ignoreArmor=True)
Attack(name="Shotel", attackNumber=3, damage=[[u]], ignoreArmor=True)
Attack(name="Silver Knight Shield", attackNumber=1, damage=[[u,u]])
Attack(name="Silver Knight Spear", attackNumber=1, damage=[[u]], damageMod=1)
Attack(name="Silver Knight Spear", attackNumber=2, damage=[[b,b]], damageMod=1)
Attack(name="Silver Knight Straight Sword", attackNumber=1, damage=[[b,b]])
Attack(name="Silver Knight Straight Sword", attackNumber=2, damage=[[b,u]])
Attack(name="Skull Lantern", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Smelter Sword", attackNumber=1, damage=[[b,b,b]])
Attack(name="Smelter Sword", attackNumber=2, damage=[[o,o]])
Attack(name="Smough's Hammer", attackNumber=1, damage=[[u,o]])
Attack(name="Smough's Hammer", attackNumber=2, damage=[[u,u,o,o]])
Attack(name="Sorcerer's Catalyst", attackNumber=1, damage=[[u]], magic=True)
Attack(name="Sorcerer's Catalyst", attackNumber=2, damage=[[b,b]], magic=True)
Attack(name="Sorcerer's Staff", attackNumber=1, damage=[[u]])
Attack(name="Sorcerer's Staff", attackNumber=2, damage=[[u,u]])
Attack(name="Sorcerer's Staff", attackNumber=3, damage=[[o]], magic=True)
Attack(name="Soul Arrow", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Soul Arrow", attackNumber=2, damage=[[b,b,b]], magic=True)
Attack(name="Soul Greatsword", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Soul Greatsword", attackNumber=2, damage=[[o,o]], magic=True)
Attack(name="Soul Spear", attackNumber=1, damage=[[b]], magic=True)
Attack(name="Soul Spear", attackNumber=2, damage=[[b,b,b]], magic=True)
Attack(name="Soulstream", attackNumber=1, damage=[[b]], magic=True)
Attack(name="Soulstream", attackNumber=2, damage=[[u]], magic=True)
Attack(name="Soulstream", attackNumber=3, damage=[[o]], magic=True)
Attack(name="Spear", attackNumber=1, damage=[[b]])
Attack(name="Spear", attackNumber=2, damage=[[b]], damageMod=1)
Attack(name="Spiked Mace", attackNumber=1, damage=[[b,u]])
Attack(name="Spiked Mace", attackNumber=2, damage=[[b,u,u]])
Attack(name="Spiked Mace", attackNumber=3, damage=[[b,u,u]])
Attack(name="Spitfire Spear", attackNumber=1, damage=[[o]], magic=True)
Attack(name="Spitfire Spear", attackNumber=2, damage=[[u,u]], magic=True)
Attack(name="Spotted Whip", attackNumber=1, damage=[[b,b]], damageMod=-1, poison=True)
Attack(name="Spotted Whip", attackNumber=2, damage=[[b,u]], damageMod=-1, poison=True)
Attack(name="Stone Greataxe", attackNumber=1, damage=[[u,u]])
Attack(name="Stone Greataxe", attackNumber=2, damage=[[u,u,u]])
Attack(name="Stone Greatsword", attackNumber=1, damage=[[b,u]], magic=True)
Attack(name="Stone Greatsword", attackNumber=2, damage=[[b,b,u]], magic=True)
Attack(name="Sunlight Straight Sword", attackNumber=1, damage=[[b,u]])
Attack(name="Sunlight Straight Sword", attackNumber=2, damage=[[u,u]])
Attack(name="Thorolund Talisman", attackNumber=1, damage=[[b,b]], magic=True)
Attack(name="Thorolund Talisman", attackNumber=2, damage=[[u,u]], magic=True)
Attack(name="Thrall Axe", attackNumber=1, damage=[[b,b]])
Attack(name="Thrall Axe", attackNumber=2, damage=[[b,u]])
Attack(name="Titanite Catch Pole", attackNumber=1, damage=[[b,u]], magic=True)
Attack(name="Titanite Catch Pole", attackNumber=2, damage=[[u,u]], magic=True)
Attack(name="Titanite Catch Pole", attackNumber=3, damage=[[u,u]], magic=True)
Attack(name="Torch", attackNumber=1, damage=[[b]], magic=True)
Attack(name="Torch", attackNumber=2, damage=[[u]], magic=True)
Attack(name="Uchigatana", attackNumber=1, damage=[[b,b]])
Attack(name="Uchigatana", attackNumber=2, damage=[[u,u]])
Attack(name="Umbral Dagger", attackNumber=1, damage=[[u,u]], damageMod=-1)
Attack(name="Umbral Dagger", attackNumber=2, damage=[[o,o]], damageMod=-1)
Attack(name="Umbral Dagger", attackNumber=3, damage=[[u,o,o]], damageMod=-1)
Attack(name="Velka's Rapier", attackNumber=1, damage=[[b]], magic=True)
Attack(name="Velka's Rapier", attackNumber=2, damage=[[b,b]], magic=True)
Attack(name="Vordt's Great Hammer", attackNumber=1, damage=[[u,u,u]])
Attack(name="Vordt's Great Hammer", attackNumber=2, damage=[[u,u,u,u]])
Attack(name="Warpick", attackNumber=1, damage=[[u,o]])
Attack(name="Warpick", attackNumber=2, damage=[[u,o,o]])
Attack(name="Warden Twinblades", attackNumber=1, damage=[[b], [b]])
Attack(name="Warden Twinblades", attackNumber=2, damage=[[b,b], [b,b]])
Attack(name="Warden Twinblades", attackNumber=3, damage=[[u,u], [u,u]])
Attack(name="Washing Pole", attackNumber=1, damage=[[b,b]])
Attack(name="Washing Pole", attackNumber=2, damage=[[u,u]])
Attack(name="Washing Pole", attackNumber=3, damage=[[u,u]], bleed=True)
Attack(name="Winged Knight Halberd", attackNumber=1, damage=[[u]])
Attack(name="Winged Knight Halberd", attackNumber=2, damage=[[u,u]])
Attack(name="Winged Knight Halberd", attackNumber=3, damage=[[u,u]])
Attack(name="Winged Knight Twin Axes", attackNumber=1, damage=[[b],[b]], damageMod=1)
Attack(name="Winged Knight Twin Axes", attackNumber=2, damage=[[u],[u]], damageMod=1)
Attack(name="Winged Knight Twin Axes", attackNumber=3, damage=[[o],[o]], damageMod=1)
Attack(name="Winged Spear", attackNumber=1, damage=[[b]], damageMod=1)
Attack(name="Winged Spear", attackNumber=2, damage=[[b,b]], damageMod=1)
Attack(name="Witch's Locks", attackNumber=1, damage=[[u]], magic=True)
Attack(name="Witch's Locks", attackNumber=2, damage=[[b,u]], magic=True)
Attack(name="Zweihander", attackNumber=1, damage=[[b,u,u]])
Attack(name="Zweihander", attackNumber=2, damage=[[b,o,o]])