builds = {
    "Assassin": {
        1: {
            1: [
                "Adventurer's Armour",
                "Black Armour",
                "Black Hand Armour (common)",
                "Dark Armour",
                "Guardian Armour",
                "Master's Attire",
                "Worker Armour",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Composite Bow",
                "Eastern Iron Shield",
                "Kukris",
                "Longbow",
                "Mannikin Claws",
                "Murakumo",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Dagger",
                "Rotten Ghru Spear",
                "Scimitar",
                "Spotted Whip",
                "Throwing Knives",
                "Assassin Armour",
                "Estoc",
                "Target Shield",
            ],
            2: [
                "Hunter Armour",
                "Painting Guardian Armour",
                "Shadow Armour",
                "Black Bow of Pharis",
                "Carthus Curved Greatsword",
                "Hard Leather Armour",
                "Flameberge",
                "Mannikin Claws",
                "Notched Whip",
                "Silver Knight Straight Sword",
                "Spotted Whip",
            ],
            3: [
                "Adventurer's Armour (Legendary)",
                "Alva Armour",
                "Chariot Lance",
                "Shadow Armour",
                "Dancer's Enchanted Swords",
                "Dark Armour (Legendary)",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Carthus Curved Sword",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Lifehunt Scythe",
                "Lucerne",
                "Silver Knight Straight Sword",
                "Umbral Dagger",
            ]
        },
        2: {
            1: [
                "Adventurer's Armour",
                "Black Armour",
                "Black Hand Armour (common)",
                "Dark Armour",
                "Guardian Armour",
                "Hunter Armour",
                "Master's Attire",
                "Painting Guardian Armour",
                "Worker Armour",
                "Black Bow of Pharis",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Composite Bow",
                "Eastern Iron Shield",
                "Flameberge",
                "Kukris",
                "Longbow",
                "Mannikin Claws",
                "Murakumo",
                "Notched Whip",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Dagger",
                "Rotten Ghru Spear",
                "Scimitar",
                "Spotted Whip",
                "Throwing Knives",
                "Assassin Armour",
                "Estoc",
                "Target Shield",
            ],
            2: [
                "Hunter Armour",
                "Painting Guardian Armour",
                "Shadow Armour",
                "Black Bow of Pharis",
                "Carthus Curved Greatsword",
                "Hard Leather Armour",
                "Flameberge",
                "Mannikin Claws",
                "Notched Whip",
                "Silver Knight Straight Sword",
                "Spotted Whip",
            ],
            3: [
                "Adventurer's Armour (Legendary)",
                "Alva Armour",
                "Chariot Lance",
                "Shadow Armour",
                "Dancer's Enchanted Swords",
                "Dark Armour (Legendary)",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Carthus Curved Sword",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Lifehunt Scythe",
                "Lucerne",
                "Silver Knight Straight Sword",
                "Umbral Dagger",
            ]
        },
        3: {
            1: [
                "Adventurer's Armour",
                "Black Armour",
                "Black Hand Armour (common)",
                "Dark Armour",
                "Guardian Armour",
                "Master's Attire",
                "Worker Armour",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Composite Bow",
                "Eastern Iron Shield",
                "Kukris",
                "Longbow",
                "Mannikin Claws",
                "Murakumo",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Dagger",
                "Rotten Ghru Spear",
                "Scimitar",
                "Spotted Whip",
                "Throwing Knives",
                "Assassin Armour",
                "Estoc",
                "Target Shield",
            ],
            2: [
                "Shadow Armour",
                "Black Bow of Pharis",
                "Carthus Curved Greatsword",
                "Claws",
                "Flameberge",
                "Mannikin Claws",
                "Murakumo",
                "Notched Whip",
                "Rapier",
                "Silver Knight Straight Sword",
                "Spotted Whip",
            ],
            3: [
                "Adventurer's Armour (Legendary)",
                "Alva Armour",
                "Chariot Lance",
                "Shadow Armour",
                "Dancer's Enchanted Swords",
                "Dark Armour (Legendary)",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Carthus Curved Sword",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Lifehunt Scythe",
                "Lucerne",
                "Silver Knight Straight Sword",
                "Umbral Dagger",
            ]
        },
        4: {
            1: [
                "Composite Bow",
                "Kukris",
                "Longbow",
                "Poison Throwing Knives",
                "Rotten Ghru Dagger",
                "Rotten Ghru Spear",
                "Scimitar",
                "Throwing Knives",
                "Assassin Armour",
                "Estoc",
                "Target Shield",
            ],
            2: [
                "Eastern Iron Shield",
                "Irithyll Rapier",
                "Flameberge",
                "Mannikin Claws",
                "Murakumo",
                "Notched Whip",
                "Rapier",
                "Spotted Whip",
                "Assassin Armour",
            ],
            3: [
                "Shadow Armour",
                "Dancer's Enchanted Swords",
                "Dark Armour (Legendary)",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Carthus Curved Sword",
                "Guardian Armour (Legendary)",
                "Lifehunt Scythe",
                "Lucerne",
                "Silver Knight Straight Sword",
            ]
        }
    },
    "Cleric": {
        1: {
            1: [
                "Cleric Armour",
                "Deacon Robes",
                "Sunless Armour",
                "Sunset Armour",
                "Worker Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Effigy Shield",
                "Four-Pronged Plow",
                "Great Mace",
                "Halberd",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Magic Barrier",
                "Med Heal",
                "Morning Star",
                "Phoenix Parma Shield",
                "Pike",
                "Sacred Oath",
                "Stone Greatsword",
                "Sunlight Shield",
                "Sunset Shield",
                "Winged Spear",
                "Cleric Robes",
                "Mace",
                "Blue Wooden Shield",
            ],
            2: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Sunset Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Great Heal",
                "Great Mace",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Archdeacon Robe",
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Obsidian Greatsword",
                "Morne's Great Hammer",
                "Sanctus",
                "Silver Knight Straight Sword",
                "Spitfire Spear",
            ]
        },
        2: {
            1: [
                "Cleric Armour",
                "Deacon Robes",
                "Sunless Armour",
                "Sunset Armour",
                "Worker Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Effigy Shield",
                "Four-Pronged Plow",
                "Great Heal",
                "Great Mace",
                "Halberd",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Magic Barrier",
                "Med Heal",
                "Morning Star",
                "Phoenix Parma Shield",
                "Pike",
                "Sacred Oath",
                "Stone Greatsword",
                "Sunlight Shield",
                "Sunset Shield",
                "Winged Spear",
                "Cleric Robes",
                "Mace",
                "Blue Wooden Shield",
            ],
            2: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Sunset Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Great Heal",
                "Great Mace",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Archdeacon Robe",
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Obsidian Greatsword",
                "Morne's Great Hammer",
                "Sanctus",
                "Silver Knight Straight Sword",
                "Spitfire Spear",
            ]
        },
        3: {
            1: [
                "Cleric Armour",
                "Deacon Robes",
                "Sunless Armour",
                "Sunset Armour",
                "Worker Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Effigy Shield",
                "Four-Pronged Plow",
                "Great Mace",
                "Halberd",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Magic Barrier",
                "Med Heal",
                "Morning Star",
                "Phoenix Parma Shield",
                "Pike",
                "Sacred Oath",
                "Stone Greatsword",
                "Sunlight Shield",
                "Sunset Shield",
                "Winged Spear",
                "Cleric Robes",
                "Mace",
                "Blue Wooden Shield",
            ],
            2: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Sunset Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Great Heal",
                "Great Mace",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Archdeacon Robe",
                "Blinding Bolt",
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Great Heal",
                "Obsidian Greatsword",
                "Morne's Great Hammer",
                "Sanctus",
                "Soothing Sunlight",
                "Silver Knight Straight Sword",
                "Spitfire Spear",
            ]
        },
        4: {
            1: [
                "Sunless Armour",
                "Worker Armour",
                "Effigy Shield",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Morning Star",
                "Phoenix Parma Shield",
                "Sunset Shield",
                "Cleric Robes",
                "Mace",
                "Blue Wooden Shield",
            ],
            2: [
                "Cleric Armour",
                "Deacon Robes",
                "Sunset Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Four-Pronged Plow",
                "Great Heal",
                "Great Mace",
                "Halberd",
                "Magic Barrier",
                "Med Heal",
                "Pike",
                "Sacred Oath",
                "Stone Greatsword",
                "Sunlight Shield",
                "Winged Spear",
            ],
            3: [
                "Archdeacon Robe",
                "Blinding Bolt",
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Great Heal",
                "Sanctus",
                "Soothing Sunlight",
                "Silver Knight Straight Sword",
            ]
        }
    },
}