builds = {
    "Assassin": {
        1: {
            1: [
                "Adventurer's Armour",
                "Black Armour",
                "Black Hand Armour",
                "Dark Armour",
                "Guardian Armour",
                "Master's Attire",
                "Worker Armour",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Composite Bow",
                "Eastern Iron Shield",
                "Kukris",
                "Longbow",
                "Mannikin Claws",
                "Murakumo",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Dagger",
                "Rotten Ghru Spear",
                "Scimitar",
                "Spotted Whip",
                "Throwing Knives",
                "Assassin Armour",
                "Estoc",
                "Target Shield",
            ],
            2: [
                "Hunter Armour",
                "Painting Guardian Armour",
                "Shadow Armour",
                "Black Bow of Pharis",
                "Carthus Curved Greatsword",
                "Hard Leather Armour",
                "Flamberge",
                "Mannikin Claws",
                "Notched Whip",
                "Silver Knight Straight Sword",
                "Spotted Whip",
            ],
            3: [
                "Adventurer's Armour (Legendary)",
                "Alva Armour",
                "Chariot Lance",
                "Shadow Armour",
                "Dancer's Enchanted Swords",
                "Dark Armour (Legendary)",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Carthus Curved Sword",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Lifehunt Scythe",
                "Lucerne",
                "Silver Knight Straight Sword",
                "Umbral Dagger",
            ]
        },
        2: {
            1: [
                "Adventurer's Armour",
                "Black Armour",
                "Black Hand Armour",
                "Dark Armour",
                "Guardian Armour",
                "Hunter Armour",
                "Master's Attire",
                "Painting Guardian Armour",
                "Worker Armour",
                "Black Bow of Pharis",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Composite Bow",
                "Eastern Iron Shield",
                "Flamberge",
                "Kukris",
                "Longbow",
                "Mannikin Claws",
                "Murakumo",
                "Notched Whip",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Dagger",
                "Rotten Ghru Spear",
                "Scimitar",
                "Spotted Whip",
                "Throwing Knives",
                "Assassin Armour",
                "Estoc",
                "Target Shield",
            ],
            2: [
                "Hunter Armour",
                "Painting Guardian Armour",
                "Shadow Armour",
                "Black Bow of Pharis",
                "Carthus Curved Greatsword",
                "Hard Leather Armour",
                "Flamberge",
                "Mannikin Claws",
                "Notched Whip",
                "Silver Knight Straight Sword",
                "Spotted Whip",
            ],
            3: [
                "Adventurer's Armour (Legendary)",
                "Alva Armour",
                "Chariot Lance",
                "Shadow Armour",
                "Dancer's Enchanted Swords",
                "Dark Armour (Legendary)",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Carthus Curved Sword",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Lifehunt Scythe",
                "Lucerne",
                "Silver Knight Straight Sword",
                "Umbral Dagger",
            ]
        },
        3: {
            1: [
                "Adventurer's Armour",
                "Black Armour",
                "Black Hand Armour",
                "Dark Armour",
                "Guardian Armour",
                "Master's Attire",
                "Worker Armour",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Composite Bow",
                "Eastern Iron Shield",
                "Kukris",
                "Longbow",
                "Mannikin Claws",
                "Murakumo",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Dagger",
                "Rotten Ghru Spear",
                "Scimitar",
                "Spotted Whip",
                "Throwing Knives",
                "Assassin Armour",
                "Estoc",
                "Target Shield",
            ],
            2: [
                "Shadow Armour",
                "Black Bow of Pharis",
                "Carthus Curved Greatsword",
                "Claws",
                "Flamberge",
                "Mannikin Claws",
                "Murakumo",
                "Notched Whip",
                "Rapier",
                "Silver Knight Straight Sword",
                "Spotted Whip",
            ],
            3: [
                "Adventurer's Armour (Legendary)",
                "Alva Armour",
                "Chariot Lance",
                "Shadow Armour",
                "Dancer's Enchanted Swords",
                "Dark Armour (Legendary)",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Carthus Curved Sword",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Lifehunt Scythe",
                "Lucerne",
                "Silver Knight Straight Sword",
                "Umbral Dagger",
            ]
        },
        4: {
            1: [
                "Composite Bow",
                "Kukris",
                "Longbow",
                "Poison Throwing Knives",
                "Rotten Ghru Dagger",
                "Rotten Ghru Spear",
                "Scimitar",
                "Throwing Knives",
                "Assassin Armour",
                "Estoc",
                "Target Shield",
            ],
            2: [
                "Eastern Iron Shield",
                "Irithyll Rapier",
                "Flamberge",
                "Mannikin Claws",
                "Murakumo",
                "Notched Whip",
                "Rapier",
                "Spotted Whip",
                "Assassin Armour",
            ],
            3: [
                "Shadow Armour",
                "Dancer's Enchanted Swords",
                "Dark Armour (Legendary)",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Carthus Curved Sword",
                "Guardian Armour (Legendary)",
                "Lifehunt Scythe",
                "Lucerne",
                "Silver Knight Straight Sword",
            ]
        }
    },
    "Cleric": {
        1: {
            1: [
                "Cleric Armour",
                "Deacon Robes",
                "Sunless Armour",
                "Sunset Armour",
                "Worker Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Effigy Shield",
                "Four-Pronged Plow",
                "Great Mace",
                "Halberd",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Magic Barrier",
                "Med Heal",
                "Morning Star",
                "Phoenix Parma Shield",
                "Pike",
                "Sacred Oath",
                "Stone Greatsword",
                "Sunlight Shield",
                "Sunset Shield",
                "Winged Spear",
                "Cleric Robes",
                "Mace",
                "Blue Wooden Shield",
            ],
            2: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Sunset Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Great Heal",
                "Great Mace",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Archdeacon Robe",
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Obsidian Greatsword",
                "Morne's Great Hammer",
                "Sanctus",
                "Silver Knight Straight Sword",
                "Spitfire Spear",
            ]
        },
        2: {
            1: [
                "Cleric Armour",
                "Deacon Robes",
                "Sunless Armour",
                "Sunset Armour",
                "Worker Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Effigy Shield",
                "Four-Pronged Plow",
                "Great Heal",
                "Great Mace",
                "Halberd",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Magic Barrier",
                "Med Heal",
                "Morning Star",
                "Phoenix Parma Shield",
                "Pike",
                "Sacred Oath",
                "Stone Greatsword",
                "Sunlight Shield",
                "Sunset Shield",
                "Winged Spear",
                "Cleric Robes",
                "Mace",
                "Blue Wooden Shield",
            ],
            2: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Sunset Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Great Heal",
                "Great Mace",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Archdeacon Robe",
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Obsidian Greatsword",
                "Morne's Great Hammer",
                "Sanctus",
                "Silver Knight Straight Sword",
                "Spitfire Spear",
            ]
        },
        3: {
            1: [
                "Cleric Armour",
                "Deacon Robes",
                "Sunless Armour",
                "Sunset Armour",
                "Worker Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Effigy Shield",
                "Four-Pronged Plow",
                "Great Mace",
                "Halberd",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Magic Barrier",
                "Med Heal",
                "Morning Star",
                "Phoenix Parma Shield",
                "Pike",
                "Sacred Oath",
                "Stone Greatsword",
                "Sunlight Shield",
                "Sunset Shield",
                "Winged Spear",
                "Cleric Robes",
                "Mace",
                "Blue Wooden Shield",
            ],
            2: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Sunset Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Great Heal",
                "Great Mace",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Archdeacon Robe",
                "Blinding Bolt",
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Great Heal",
                "Obsidian Greatsword",
                "Morne's Great Hammer",
                "Sanctus",
                "Soothing Sunlight",
                "Silver Knight Straight Sword",
                "Spitfire Spear",
            ]
        },
        4: {
            1: [
                "Sunless Armour",
                "Worker Armour",
                "Effigy Shield",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Morning Star",
                "Phoenix Parma Shield",
                "Sunset Shield",
                "Cleric Robes",
                "Mace",
                "Blue Wooden Shield",
            ],
            2: [
                "Cleric Armour",
                "Deacon Robes",
                "Sunset Armour",
                "Atonement",
                "Cleric's Candlestick",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Four-Pronged Plow",
                "Great Heal",
                "Great Mace",
                "Halberd",
                "Magic Barrier",
                "Med Heal",
                "Pike",
                "Sacred Oath",
                "Stone Greatsword",
                "Sunlight Shield",
                "Winged Spear",
            ],
            3: [
                "Archdeacon Robe",
                "Blinding Bolt",
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Great Heal",
                "Sanctus",
                "Soothing Sunlight",
                "Silver Knight Straight Sword",
            ]
        }
    },
    "Herald": {
        1: {
            1: [
                "Cathedral Knight Armour",
                "Deacon Robes",
                "Embraced Armour of Favour",
                "Sunless Armour",
                "Sunset Armour",
                "Worker Armour",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Effigy Shield",
                "Four-Pronged Plow",
                "Golden Wing Crest Shield",
                "Great Mace",
                "Halberd",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Lothric's Holy Sword",
                "Morning Star",
                "Phoenix Parma Shield",
                "Pike",
                "Replenishment",
                "Stone Greatsword",
                "Sunlight Shield",
                "Thorolund Talisman",
                "Winged Spear",
                "Herald Armour",
                "Kite Shield",
                "Spear",
                "Talisman",
            ],
            2: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Sunset Armour",
                "Four-Pronged Plow",
                "Golden Wing Crest Shield",
                "Great Mace",
                "Lothric's Holy Sword",
                "Pike",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Bountiful Sunlight",
                "Obsidian Greatsword",
                "Partizan",
                "Saint Bident",
                "Spitfire Spear",
                "Silver Knight Straight Sword",
            ]
        },
        2: {
            1: [
                "Cathedral Knight Armour",
                "Deacon Robes",
                "Embraced Armour of Favour",
                "Sunless Armour",
                "Sunset Armour",
                "Worker Armour",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Effigy Shield",
                "Four-Pronged Plow",
                "Golden Wing Crest Shield",
                "Great Mace",
                "Halberd",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Lothric's Holy Sword",
                "Morning Star",
                "Phoenix Parma Shield",
                "Pike",
                "Replenishment",
                "Stone Greatsword",
                "Sunlight Shield",
                "Thorolund Talisman",
                "Winged Spear",
                "Herald Armour",
                "Kite Shield",
                "Spear",
                "Talisman",
            ],
            2: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Sunset Armour",
                "Four-Pronged Plow",
                "Golden Wing Crest Shield",
                "Great Mace",
                "Lothric's Holy Sword",
                "Pike",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Bountiful Sunlight",
                "Obsidian Greatsword",
                "Partizan",
                "Saint Bident",
                "Spitfire Spear",
                "Silver Knight Straight Sword",
            ]
        },
        3: {
            1: [
                "Cathedral Knight Armour",
                "Deacon Robes",
                "Embraced Armour of Favour",
                "Sunless Armour",
                "Sunset Armour",
                "Worker Armour",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Effigy Shield",
                "Four-Pronged Plow",
                "Golden Wing Crest Shield",
                "Great Mace",
                "Halberd",
                "Heal",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Lothric's Holy Sword",
                "Morning Star",
                "Phoenix Parma Shield",
                "Pike",
                "Replenishment",
                "Stone Greatsword",
                "Sunlight Shield",
                "Thorolund Talisman",
                "Winged Spear",
                "Herald Armour",
                "Kite Shield",
                "Spear",
                "Talisman",
            ],
            2: [
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Sunset Armour",
                "Four-Pronged Plow",
                "Golden Wing Crest Shield",
                "Great Mace",
                "Lothric's Holy Sword",
                "Pike",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Blinding Bolt",
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Bountiful Light",
                "Bountiful Sunlight",
                "Obsidian Greatsword",
                "Partizan",
                "Sanctus",
                "Saint Bident",
                "Soothing Sunlight",
                "Spitfire Spear",
                "Silver Knight Straight Sword",
            ]
        },
        4: {
            1: [
                "Sunless Armour",
                "Worker Armour",
                "Effigy Shield",
                "Heal Aid",
                "Hollow Soldier Shield",
                "Morning Star",
                "Phoenix Parma Shield",
                "Herald Armour",
                "Kite Shield",
                "Spear",
                "Talisman",
            ],
            2: [
                "Sunset Armour",
                "Worker Armour",
                "Crystal Shield",
                "Dragon Crest Shield",
                "Four-Pronged Plow",
                "Golden Wing Crest Shield",
                "Great Mace",
                "Halberd",
                "Heal",
                "Hollow Soldier Shield",
                "Lothric's Holy Sword",
                "Morning Star",
                "Pike",
                "Replenishment",
                "Stone Greatsword",
                "Sunlight Shield",
                "Thorolund Talisman",
                "Winged Spear",
            ],
            3: [
                "Blinding Bolt",
                "Embraced Armour of Favour (Legendary)",
                "Paladin Armour",
                "Bountiful Light",
                "Bountiful Sunlight",
                "Partizan",
                "Sanctus",
                "Soothing Sunlight",
                "Silver Knight Straight Sword",
            ]
        }
    },
    "Knight": {
        1: {
            1: [
                "Catarina Armour",
                "Drang Armour",
                "Lothric Knight Armour",
                "Stone Knight Armour",
                "Worker Armour",
                "Silver Knight Armour",
                "Alonne Greatbow",
                "Broadsword",
                "Claymore",
                "Dragonslayer Greatbow",
                "Bonewheel Shield",
                "Crescent Axe",
                "Morion Blade",
                "Exile Greatsword",
                "Pierce Shield",
                "Porcine Shield",
                "Silver Eagle Kite Shield",
                "Spider Shield",
                "Thrall Axe",
                "Knight Armour",
                "Long Sword",
                "Kite Shield",
            ],
            2: [
                "Black Knight Armour",
                "Black Knight Armour (Legendary)",
                "Catarina Armour (Legendary)",
                "Hard Leather Armour",
                "Old Ironclad Armour",
                "Paladin Armour",
                "Silver Knight Armour",
                "Broadsword",
                "Claymore",
                "Dragonslayer Greatbow",
                "Great Scythe",
                "Greataxe",
                "Melinda's Greataxe",
                "Morion Blade",
                "Silver Knight Straight Sword",
                "Stone Greataxe",
                "Stone Greatshield",
                "Zweihander",
            ],
            3: [
                "Black Knight Armour (Legendary)",
                "Hard Leather Armour",
                "Paladin Armour",
                "Dark Sword",
                "Dragon King Greataxe",
                "Fume Ultra Greatsword",
                "Giant Stone Axe",
                "Black Iron Greatshield",
                "Greatsword of Artorias",
                "Falchion",
                "Iron King Hammer",
                "Great Scythe",
                "Greataxe",
                "Silver Knight Straight Sword",
                "Steel Armour",
                "Twin Dragon Greatshield",
                "Winged Knight Halberd",
                "Zweihander",
            ]
        },
        2: {
            1: [
                "Armour of Thorns",
                "Black Knight Armour",
                "Catarina Armour",
                "Drang Armour",
                "Lothric Knight Armour",
                "Catarina Armour (Legendary)",
                "Stone Knight Armour",
                "Worker Armour",
                "Elite Knight Armour",
                "Faraam Armour",
                "Old Ironclad Armour",
                "Silver Knight Armour",
                "Drake Sword",
                "Alonne Greatbow",
                "Gargoyle Tail Axe",
                "Broadsword",
                "Claymore",
                "Greatsword",
                "Dragonslayer Greatbow",
                "Cursed Greatsword of Artorias",
                "Demon's Great Hammer",
                "Bonewheel Shield",
                "Crescent Axe",
                "Lothric Knight Greatsword",
                "Melinda's Greataxe",
                "Morion Blade",
                "Pursuer's Ultra Greatsword",
                "Exile Greatsword",
                "Smelter Sword",
                "Smough's Armour",
                "Smough's Hammer",
                "Pierce Shield",
                "Porcine Shield",
                "Silver Eagle Kite Shield",
                "Stone Greataxe",
                "Stone Greatshield",
                "Spider Shield",
                "Spiked Shield",
                "Titanite Catch Pole",
                "Thrall Axe",
                "Knight Armour",
                "Long Sword",
                "Kite Shield",
            ],
            2: [
                "Black Knight Armour",
                "Black Knight Armour (Legendary)",
                "Catarina Armour (Legendary)",
                "Hard Leather Armour",
                "Old Ironclad Armour",
                "Paladin Armour",
                "Silver Knight Armour",
                "Broadsword",
                "Claymore",
                "Dragonslayer Greatbow",
                "Great Scythe",
                "Greataxe",
                "Melinda's Greataxe",
                "Morion Blade",
                "Silver Knight Straight Sword",
                "Stone Greataxe",
                "Stone Greatshield",
                "Zweihander",
            ],
            3: [
                "Black Knight Armour (Legendary)",
                "Hard Leather Armour",
                "Paladin Armour",
                "Dark Sword",
                "Dragon King Greataxe",
                "Fume Ultra Greatsword",
                "Giant Stone Axe",
                "Black Iron Greatshield",
                "Greatsword of Artorias",
                "Falchion",
                "Iron King Hammer",
                "Great Scythe",
                "Greataxe",
                "Silver Knight Straight Sword",
                "Steel Armour",
                "Twin Dragon Greatshield",
                "Winged Knight Halberd",
                "Zweihander",
            ]
        },
        3: {
            1: [
                "Catarina Armour",
                "Drang Armour",
                "Lothric Knight Armour",
                "Stone Knight Armour",
                "Worker Armour",
                "Silver Knight Armour",
                "Alonne Greatbow",
                "Broadsword",
                "Claymore",
                "Dragonslayer Greatbow",
                "Bonewheel Shield",
                "Crescent Axe",
                "Morion Blade",
                "Exile Greatsword",
                "Pierce Shield",
                "Porcine Shield",
                "Silver Eagle Kite Shield",
                "Spider Shield",
                "Thrall Axe",
                "Knight Armour",
                "Long Sword",
                "Kite Shield",
            ],
            2: [
                "Black Knight Armour",
                "Catarina Armour (Legendary)",
                "Old Ironclad Armour",
                "Silver Knight Armour",
                "Broadsword",
                "Claymore",
                "Dragonslayer Greatbow",
                "Great Scythe",
                "Greataxe",
                "Melinda's Greataxe",
                "Morion Blade",
                "Silver Knight Straight Sword",
                "Stone Greataxe",
                "Stone Greatshield",
                "Zweihander",
            ],
            3: [
                "Black Knight Armour (Legendary)",
                "Hard Leather Armour",
                "Paladin Armour",
                "Dark Sword",
                "Dragon King Greataxe",
                "Fume Ultra Greatsword",
                "Giant Stone Axe",
                "Black Iron Greatshield",
                "Greatsword of Artorias",
                "Iron King Hammer",
                "Great Scythe",
                "Greataxe",
                "Silver Knight Straight Sword",
                "Steel Armour",
                "Winged Knight Halberd",
                "Zweihander",
            ]
        },
        4: {
            1: [
                "Drang Armour",
                "Lothric Knight Armour",
                "Worker Armour",
                "Pierce Shield",
                "Silver Eagle Kite Shield",
                "Thrall Axe",
                "Knight Armour",
                "Long Sword",
                "Kite Shield",
            ],
            2: [
                "Black Knight Armour",
                "Catarina Armour",
                "Catarina Armour (Legendary)",
                "Stone Knight Armour",
                "Old Ironclad Armour",
                "Silver Knight Armour",
                "Alonne Greatbow",
                "Broadsword",
                "Claymore",
                "Dragonslayer Greatbow",
                "Bonewheel Shield",
                "Crescent Axe",
                "Morion Blade",
                "Exile Greatsword",
                "Porcine Shield",
                "Stone Greataxe",
                "Stone Greatshield",
                "Spider Shield",
            ],
            3: [
                "Armour of Thorns",
                "Elite Knight Armour",
                "Dark Sword",
                "Giant Stone Axe",
                "Greatsword of Artorias",
                "Great Scythe",
                "Greataxe",
                "Melinda's Greataxe",
                "Silver Knight Straight Sword",
                "Steel Armour",
                "Zweihander",
            ]
        }
    },
    "Mercenary": {
        1: {
            1: [
                "Adventurer's Armour",
                "Black Armour",
                "Black Hand Armour",
                "Black Leather Armour",
                "Dark Armour",
                "Guardian Armour",
                "Master's Attire",
                "Painting Guardian Armour",
                "Silver Knight Armour",
                "Worker Armour",
                "Alonne Greatbow",
                "Black Knight Sword",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Crest Shield",
                "Crystal Straight Sword",
                "Dragonslayer Greatbow",
                "Eastern Iron Shield",
                "Kukris",
                "Longbow",
                "Lothric Knight Greatsword",
                "Mannikin Claws",
                "Morion Blade",
                "Murakumo",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Spear",
                "Scimitar",
                "Shortsword",
                "Thrall Axe",
                "Throwing Knives",
                "Warden Twinblades",
                "Sellsword Twinblades",
                "Sellsword Armour",
                "Wooden Shield",
            ],
            2: [
                "Black Leather Armour",
                "Hard Leather Armour",
                "Hunter Armour",
                "Master's Attire",
                "Silver Knight Armour",
                "Black Bow of Pharis",
                "Black Knight Sword",
                "Carthus Curved Greatsword",
                "Crystal Straight Sword",
                "Dragonslayer Greatbow",
                "Flamberge",
                "Lothric Knight Greatsword",
                "Mannikin Claws",
                "Morion Blade",
                "Notched Whip",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Dark Armour (Legendary)",
                "Eastern Armour",
                "Chariot Lance",
                "Guardian Armour (Legendary)",
                "Dancer's Enchanted Swords",
                "Dark Sword",
                "Drakewing Ultra Greatsword",
                "Dragon King Greataxe",
                "Gold Tracer",
                "Gotthard Twinswords",
                "Drang Hammers",
                "Onikiri and Ubadachi",
                "Silver Knight Straight Sword",
                "Steel Armour",
                "Winged Knight Twin Axes",
            ]
        },
        2: {
            1: [
                "Adventurer's Armour",
                "Black Armour",
                "Black Hand Armour",
                "Black Leather Armour",
                "Dark Armour",
                "Guardian Armour",
                "Hunter Armour",
                "Master's Attire",
                "Painting Guardian Armour",
                "Silver Knight Armour",
                "Worker Armour",
                "Alonne Greatbow",
                "Black Bow of Pharis",
                "Black Knight Sword",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Crest Shield",
                "Crystal Straight Sword",
                "Dragonslayer Greatbow",
                "Eastern Iron Shield",
                "Flamberge",
                "Kukris",
                "Longbow",
                "Lothric Knight Greatsword",
                "Mannikin Claws",
                "Morion Blade",
                "Murakumo",
                "Notched Whip",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Spear",
                "Scimitar",
                "Shortsword",
                "Thrall Axe",
                "Throwing Knives",
                "Warden Twinblades",
                "Sellsword Twinblades",
                "Sellsword Armour",
                "Wooden Shield",
            ],
            2: [
                "Black Leather Armour",
                "Hard Leather Armour",
                "Hunter Armour",
                "Master's Attire",
                "Silver Knight Armour",
                "Black Bow of Pharis",
                "Black Knight Sword",
                "Carthus Curved Greatsword",
                "Crystal Straight Sword",
                "Dragonslayer Greatbow",
                "Flamberge",
                "Lothric Knight Greatsword",
                "Mannikin Claws",
                "Morion Blade",
                "Notched Whip",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Dark Armour (Legendary)",
                "Eastern Armour",
                "Chariot Lance",
                "Guardian Armour (Legendary)",
                "Dancer's Enchanted Swords",
                "Dark Sword",
                "Drakewing Ultra Greatsword",
                "Dragon King Greataxe",
                "Gold Tracer",
                "Gotthard Twinswords",
                "Drang Hammers",
                "Onikiri and Ubadachi",
                "Silver Knight Straight Sword",
                "Steel Armour",
                "Winged Knight Twin Axes",
            ]
        },
        3: {
            1: [
                "Adventurer's Armour",
                "Black Armour",
                "Black Hand Armour",
                "Black Leather Armour",
                "Dark Armour",
                "Guardian Armour",
                "Master's Attire",
                "Painting Guardian Armour",
                "Silver Knight Armour",
                "Worker Armour",
                "Alonne Greatbow",
                "Black Knight Sword",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Crest Shield",
                "Crystal Straight Sword",
                "Dragonslayer Greatbow",
                "Eastern Iron Shield",
                "Kukris",
                "Longbow",
                "Lothric Knight Greatsword",
                "Mannikin Claws",
                "Morion Blade",
                "Murakumo",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Spear",
                "Scimitar",
                "Shortsword",
                "Thrall Axe",
                "Throwing Knives",
                "Warden Twinblades",
                "Sellsword Twinblades",
                "Sellsword Armour",
                "Wooden Shield",
            ],
            2: [
                "Black Leather Armour",
                "Hard Leather Armour",
                "Hunter Armour",
                "Master's Attire",
                "Silver Knight Armour",
                "Black Bow of Pharis",
                "Black Knight Sword",
                "Carthus Curved Greatsword",
                "Crystal Straight Sword",
                "Dragonslayer Greatbow",
                "Flamberge",
                "Lothric Knight Greatsword",
                "Mannikin Claws",
                "Morion Blade",
                "Notched Whip",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Dark Armour (Legendary)",
                "Eastern Armour",
                "Chariot Lance",
                "Guardian Armour (Legendary)",
                "Dancer's Enchanted Swords",
                "Dark Sword",
                "Drakewing Ultra Greatsword",
                "Dragon King Greataxe",
                "Gold Tracer",
                "Gotthard Twinswords",
                "Drang Hammers",
                "Onikiri and Ubadachi",
                "Silver Knight Straight Sword",
                "Steel Armour",
                "Winged Knight Twin Axes",
            ]
        },
        4: {
            1: [
                "Crest Shield",
                "Kukris",
                "Longbow",
                "Poison Throwing Knives",
                "Rotten Ghru Spear",
                "Thrall Axe",
                "Throwing Knives",
                "Sellsword Twinblades",
                "Sellsword Armour",
                "Wooden Shield",
            ],
            2: [
                "Adventurer's Armour",
                "Black Armour",
                "Black Hand Armour",
                "Black Leather Armour",
                "Dark Armour",
                "Guardian Armour",
                "Master's Attire",
                "Painting Guardian Armour",
                "Silver Knight Armour",
                "Worker Armour",
                "Alonne Greatbow",
                "Black Bow of Pharis",
                "Black Knight Sword",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Crystal Straight Sword",
                "Dragonslayer Greatbow",
                "Eastern Iron Shield",
                "Flamberge",
                "Lothric Knight Greatsword",
                "Mannikin Claws",
                "Morion Blade",
                "Murakumo",
                "Notched Whip",
                "Rapier",
                "Scimitar",
                "Shortsword",
                "Warden Twinblades",
            ],
            3: [
                "Adventurer's Armour (Legendary)",
                "Dark Armour (Legendary)",
                "Eastern Armour",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Hunter Armour",
                "Dancer's Enchanted Swords",
                "Dark Sword",
                "Drakewing Ultra Greatsword",
                "Black Bow of Pharis",
                "Gold Tracer",
                "Gotthard Twinswords",
                "Flamberge",
                "Large Leather Shield",
                "Notched Whip",
                "Onikiri and Ubadachi",
                "Silver Knight Straight Sword",
                "Steel Armour",
            ]
        }
    },
    "Pyromancer": {
        1: {
            1: [
                "Cornyx's Robes",
                "Worker Armour",
                "Xanthous Robes",
                "Black Firebombs",
                "East-West Shield",
                "Fire Surge",
                "Fireball",
                "Firebombs",
                "Force",
                "Golden Ritual Spear",
                "Great Combustion",
                "Great Magic Weapon",
                "Immolation Tinder",
                "Red and White Round Shield",
                "Soul Arrow",
                "Soul Spear",
                "Soulstream",
                "Witch's Locks",
                "Pyromancy Flame",
                "Caduceus Round Shield",
                "Pyromancer Garb",
                "Hand Axe",
            ],
            2: [
                "Cornyx's Robes",
                "Xanthous Robes",
                "Black Firebombs",
                "Black Knight Greataxe",
                "Fire Surge",
                "Golden Ritual Spear",
                "Great Combustion",
                "Immolation Tinder",
                "Silver Knight Straight Sword",
                "Soul Spear",
                "Stone Parma",
            ],
            3: [
                "Xanthous Robes",
                "Black Knight Greataxe",
                "Fire Surge",
                "Fire Whip",
                "Gargoyle's Shield",
                "Golden Ritual Spear",
                "Great Chaos Fireball",
                "Great Combustion",
                "Immolation Tinder",
                "Pursuers",
                "Silver Knight Straight Sword",
                "Stone Parma",
            ]
        },
        2: {
            1: [
                "Cornyx's Robes",
                "Worker Armour",
                "Xanthous Robes",
                "Black Firebombs",
                "Black Knight Greataxe",
                "East-West Shield",
                "Fire Surge",
                "Fireball",
                "Firebombs",
                "Force",
                "Golden Ritual Spear",
                "Great Combustion",
                "Great Magic Weapon",
                "Immolation Tinder",
                "Red and White Round Shield",
                "Soul Arrow",
                "Soul Spear",
                "Soulstream",
                "Stone Parma",
                "Witch's Locks",
                "Pyromancy Flame",
                "Caduceus Round Shield",
                "Pyromancer Garb",
                "Hand Axe",
            ],
            2: [
                "Cornyx's Robes",
                "Xanthous Robes",
                "Black Firebombs",
                "Black Knight Greataxe",
                "Fire Surge",
                "Golden Ritual Spear",
                "Great Combustion",
                "Immolation Tinder",
                "Silver Knight Straight Sword",
                "Soul Spear",
                "Stone Parma",
            ],
            3: [
                "Xanthous Robes",
                "Black Knight Greataxe",
                "Fire Surge",
                "Fire Whip",
                "Gargoyle's Shield",
                "Golden Ritual Spear",
                "Great Chaos Fireball",
                "Great Combustion",
                "Immolation Tinder",
                "Pursuers",
                "Silver Knight Straight Sword",
                "Stone Parma",
            ]
        },
        3: {
            1: [
                "Cornyx's Robes",
                "Worker Armour",
                "Xanthous Robes",
                "Black Firebombs",
                "East-West Shield",
                "Fire Surge",
                "Fireball",
                "Firebombs",
                "Force",
                "Golden Ritual Spear",
                "Great Combustion",
                "Great Magic Weapon",
                "Immolation Tinder",
                "Red and White Round Shield",
                "Soul Arrow",
                "Soul Spear",
                "Soulstream",
                "Witch's Locks",
                "Pyromancy Flame",
                "Caduceus Round Shield",
                "Pyromancer Garb",
                "Hand Axe",
            ],
            2: [
                "Cornyx's Robes",
                "Xanthous Robes",
                "Black Firebombs",
                "Black Knight Greataxe",
                "Fire Surge",
                "Golden Ritual Spear",
                "Great Combustion",
                "Immolation Tinder",
                "Silver Knight Straight Sword",
                "Soul Spear",
                "Stone Parma",
            ],
            3: [
                "Xanthous Robes",
                "Black Knight Greataxe",
                "Fire Surge",
                "Fire Whip",
                "Gargoyle's Shield",
                "Golden Ritual Spear",
                "Great Chaos Fireball",
                "Great Combustion",
                "Immolation Tinder",
                "Pursuers",
                "Silver Knight Straight Sword",
                "Stone Parma",
            ]
        },
        4: {
            1: [
                "Worker Armour",
                "Firebombs",
                "Force",
                "Great Magic Weapon",
                "Soul Arrow",
                "Pyromancy Flame",
                "Caduceus Round Shield",
                "Pyromancer Garb",
                "Hand Axe",
            ],
            2: [
                "Cornyx's Robes",
                "Xanthous Robes",
                "Black Firebombs",
                "Black Knight Greataxe",
                "Fire Surge",
                "Golden Ritual Spear",
                "Great Combustion",
                "Immolation Tinder",
                "Soul Spear",
            ],
            3: [
                "Xanthous Robes",
                "Black Knight Greataxe",
                "Fire Surge",
                "Gargoyle's Shield",
                "Golden Ritual Spear",
                "Great Combustion",
                "Immolation Tinder",
                "Pursuers",
            ]
        }
    },
    "Sorcerer": {
        1: {
            1: [
                "Aural Decoy",
                "Black Armour",
                "Black Hand Armour",
                "Claws",
                "Court Sorcerer Robes",
                "Crimson Robes",
                "Dark Armour",
                "Dragonscale Armour",
                "East-West Shield",
                "Fireball",
                "Force",
                "Gold-Hemmed Black Robes",
                "Guardian Armour",
                "Magic Shield",
                "Mannikin Claws",
                "Poison Mist",
                "Poison Throwing Knives",
                "Rapier",
                "Skull Lantern",
                "Soul Arrow",
                "Soulstream",
                "Torch",
                "Velka's Rapier",
                "Witch's Locks",
                "Worker Armour",
                "Sorcerer's Catalyst",
                "Sorcerer Robes",
                "Mail Breaker",
                "Leather Shield",
            ],
            2: [
                "Crimson Robes (Legendary)",
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Mannikin Claws",
                "Parrying Dagger",
                "Silver Knight Straight Sword",
                "Velka's Rapier",
            ],
            3: [
                "Alonne Armour",
                "Crimson Robes (Legendary)",
                "Crystal Hail",
                "Dark Armour (Legendary)",
                "Gold-Hemmed Black Robes (Legendary)",
                "Guardian Armour (Legendary)",
                "Homing Crystal Soulmass",
                "Parrying Dagger",
                "Pursuers",
                "Silver Knight Straight Sword",
                "Soul Greatsword",
            ]
        },
        2: {
            1: [
                "Aural Decoy",
                "Black Armour",
                "Black Hand Armour",
                "Claws",
                "Court Sorcerer Robes",
                "Crimson Robes",
                "Dark Armour",
                "Dragonscale Armour",
                "East-West Shield",
                "Fireball",
                "Force",
                "Gold-Hemmed Black Robes",
                "Guardian Armour",
                "Magic Shield",
                "Mannikin Claws",
                "Parrying Dagger",
                "Poison Mist",
                "Poison Throwing Knives",
                "Rapier",
                "Skull Lantern",
                "Soul Arrow",
                "Soulstream",
                "Torch",
                "Velka's Rapier",
                "Witch's Locks",
                "Worker Armour",
                "Sorcerer's Catalyst",
                "Sorcerer Robes",
                "Mail Breaker",
                "Leather Shield",
            ],
            2: [
                "Crimson Robes (Legendary)",
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Mannikin Claws",
                "Parrying Dagger",
                "Silver Knight Straight Sword",
                "Velka's Rapier",
            ],
            3: [
                "Alonne Armour",
                "Crimson Robes (Legendary)",
                "Crystal Hail",
                "Dark Armour (Legendary)",
                "Gold-Hemmed Black Robes (Legendary)",
                "Guardian Armour (Legendary)",
                "Homing Crystal Soulmass",
                "Parrying Dagger",
                "Pursuers",
                "Silver Knight Straight Sword",
                "Soul Greatsword",
            ]
        },
        3: {
            1: [
                "Aural Decoy",
                "Black Armour",
                "Black Hand Armour",
                "Claws",
                "Court Sorcerer Robes",
                "Crimson Robes",
                "Dark Armour",
                "Dragonscale Armour",
                "East-West Shield",
                "Fireball",
                "Force",
                "Gold-Hemmed Black Robes",
                "Guardian Armour",
                "Magic Shield",
                "Mannikin Claws",
                "Poison Mist",
                "Poison Throwing Knives",
                "Rapier",
                "Skull Lantern",
                "Soul Arrow",
                "Soulstream",
                "Torch",
                "Velka's Rapier",
                "Witch's Locks",
                "Worker Armour",
                "Sorcerer's Catalyst",
                "Sorcerer Robes",
                "Mail Breaker",
                "Leather Shield",
            ],
            2: [
                "Crimson Robes (Legendary)",
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Mannikin Claws",
                "Parrying Dagger",
                "Silver Knight Straight Sword",
                "Velka's Rapier",
            ],
            3: [
                "Alonne Armour",
                "Chester's Set",
                "Crimson Robes (Legendary)",
                "Crystal Hail",
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Homing Crystal Soulmass",
                "Irithyll Rapier",
                "Mannikin Claws",
                "Parrying Dagger",
                "Pursuers",
                "Silver Knight Straight Sword",
                "Soul Greatsword",
                "Velka's Rapier",
            ]
        },
        4: {
            1: [
                "Aural Decoy",
                "Court Sorcerer Robes",
                "Crimson Robes",
                "Fireball",
                "Force",
                "Gold-Hemmed Black Robes",
                "Poison Mist",
                "Poison Throwing Knives",
                "Skull Lantern",
                "Soul Arrow",
                "Soulstream",
                "Torch",
                "Worker Armour",
                "Sorcerer's Catalyst",
                "Sorcerer Robes",
                "Mail Breaker",
                "Leather Shield",
            ],
            2: [
                "Black Armour",
                "Black Hand Armour",
                "Claws",
                "Court Sorcerer Robes",
                "Crimson Robes",
                "Dark Armour",
                "Dragonscale Armour",
                "East-West Shield",
                "Gold-Hemmed Black Robes",
                "Guardian Armour",
                "Magic Shield",
                "Mannikin Claws",
                "Parrying Dagger",
                "Rapier",
                "Velka's Rapier",
                "Witch's Locks",
                "Worker Armour",
            ],
            3: [
                "Alonne Armour",
                "Chester's Set",
                "Crimson Robes (Legendary)",
                "Crystal Hail",
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Homing Crystal Soulmass",
                "Irithyll Rapier",
                "Mannikin Claws",
                "Parrying Dagger",
                "Pursuers",
                "Silver Knight Straight Sword",
                "Soul Greatsword",
                "Velka's Rapier",
            ]
        }
    },
    "Thief": {
        1: {
            1: [
                "Black Armour",
                "Black Hand Armour",
                "Black Hand Armour (Thief)",
                "Master's Attire",
                "Worker Armour",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Eastern Iron Shield",
                "Kukris",
                "Longbow",
                "Mannikin Claws",
                "Murakumo",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Spear",
                "Scimitar",
                "Shotel",
                "Small Leather Shield",
                "Throwing Knives",
                "Bandit Knife",
                "Deserter Armour",
                "Shortbow",
                "Iron Round Shield",
            ],
            2: [
                "Adventurer's Armour (Legendary)",
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Hunter Armour",
                "Painting Guardian Armour",
                "Black Bow of Pharis",
                "Carthus Curved Greatsword",
                "Flamberge",
                "Mannikin Claws",
                "Notched Whip",
                "Shotel",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Adventurer's Armour (Legendary)",
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Chariot Lance",
                "Dancer's Enchanted Swords",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Hawkwood's Shield",
                "Lifehunt Scythe",
                "Royal Dirk",
                "Silver Knight Straight Sword",
            ]
        },
        2: {
            1: [
                "Black Armour",
                "Black Hand Armour",
                "Black Hand Armour (Thief)",
                "Hunter Armour",
                "Master's Attire",
                "Painting Guardian Armour",
                "Worker Armour",
                "Black Bow of Pharis",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Eastern Iron Shield",
                "Flamberge",
                "Kukris",
                "Longbow",
                "Mannikin Claws",
                "Murakumo",
                "Notched Whip",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Spear",
                "Scimitar",
                "Shotel",
                "Small Leather Shield",
                "Throwing Knives",
                "Bandit Knife",
                "Deserter Armour",
                "Shortbow",
                "Iron Round Shield",
            ],
            2: [
                "Adventurer's Armour (Legendary)",
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Hunter Armour",
                "Painting Guardian Armour",
                "Black Bow of Pharis",
                "Carthus Curved Greatsword",
                "Flamberge",
                "Mannikin Claws",
                "Notched Whip",
                "Shotel",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Adventurer's Armour (Legendary)",
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Chariot Lance",
                "Dancer's Enchanted Swords",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Hawkwood's Shield",
                "Lifehunt Scythe",
                "Royal Dirk",
                "Silver Knight Straight Sword",
            ]
        },
        3: {
            1: [
                "Black Armour",
                "Black Hand Armour",
                "Black Hand Armour (Thief)",
                "Master's Attire",
                "Worker Armour",
                "Blacksteel Katana",
                "Carthus Curved Greatsword",
                "Claws",
                "Eastern Iron Shield",
                "Kukris",
                "Longbow",
                "Mannikin Claws",
                "Murakumo",
                "Poison Throwing Knives",
                "Rapier",
                "Rotten Ghru Spear",
                "Scimitar",
                "Shotel",
                "Small Leather Shield",
                "Throwing Knives",
                "Bandit Knife",
                "Deserter Armour",
                "Shortbow",
                "Iron Round Shield",
            ],
            2: [
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Hunter Armour",
                "Painting Guardian Armour",
                "Black Bow of Pharis",
                "Carthus Curved Greatsword",
                "Flamberge",
                "Mannikin Claws",
                "Notched Whip",
                "Shotel",
                "Silver Knight Straight Sword",
            ],
            3: [
                "Adventurer's Armour (Legendary)",
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Hard Leather Armour",
                "Chariot Lance",
                "Dancer's Enchanted Swords",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Hawkwood's Shield",
                "Lifehunt Scythe",
                "Royal Dirk",
                "Silver Knight Straight Sword",
            ]
        },
        4: {
            1: [
                "Kukris",
                "Longbow",
                "Poison Throwing Knives",
                "Rotten Ghru Spear",
                "Scimitar",
                "Throwing Knives",
                "Bandit Knife",
                "Deserter Armour",
                "Shortbow",
                "Iron Round Shield",
            ],
            2: [
                "Black Armour",
                "Black Hand Armour",
                "Black Hand Armour (Thief)",
                "Master's Attire",
                "Black Bow of Pharis",
                "Carthus Curved Greatsword",
                "Claws",
                "Flamberge",
                "Mannikin Claws",
                "Murakumo",
                "Notched Whip",
                "Rapier",
                "Shotel",
                "Small Leather Shield",
            ],
            3: [
                "Dark Armour (Legendary)",
                "Guardian Armour (Legendary)",
                "Dancer's Enchanted Swords",
                "Drakewing Ultra Greatsword",
                "Gold Tracer",
                "Lifehunt Scythe",
                "Royal Dirk",
                "Silver Knight Straight Sword",
            ]
        }
    },
    "Warrior": {
        1: {
            1: [
                "Black Iron Armour",
                "Black Iron Armour (Legendary)",
                "Black Knight Armour",
                "Drang Armour",
                "Exile Armour",
                "Stone Knight Armour",
                "Sunless Armour",
                "Worker Armour",
                "Alonne Greatbow",
                "Bonewheel Shield",
                "Caestus",
                "Crescent Axe",
                "Dragon Crest Shield",
                "Dragonslayer Greatbow",
                "Effigy Shield",
                "Exile Greatsword",
                "Four-Pronged Plow",
                "Great Scythe",
                "Great Wooden Hammer",
                "Greataxe",
                "Lothric Knight Greatsword",
                "Morion Blade",
                "Pierce Shield",
                "Pike",
                "Porcine Shield",
                "Reinforced Club",
                "Silver Knight Shield",
                "Spiked Mace",
                "Stone Greatsword",
                "Thrall Axe",
                "Battle Axe",
                "Northern Armour",
                "Round Shield",
            ],
            2: [
                "Black Iron Armour (Legendary)",
                "Black Knight Armour (Legendary)",
                "Catarina Armour (Legendary)",
                "Old Ironclad Armour",
                "Paladin Armour",
                "Silver Knight Armour",
                "Bloodshield",
                "Claymore",
                "Great Scythe",
                "Greataxe",
                "Lothric Knight Greatsword",
                "Melinda's Greataxe",
                "Morion Blade",
                "Silver Knight Shield",
                "Silver Knight Straight Sword",
                "Spiked Mace",
                "Stone Greataxe",
                "Stone Greatshield",
                "Zweihander",
            ],
            3: [
                "Silver Knight Armour",
                "Smelter Demon Armour",
                "Steel Armour",
                "Balder Side Sword",
                "Claymore",
                "Dark Sword",
                "Dragon King Greataxe",
                "Dragon Tooth",
                "Dragonslayer Spear",
                "Dragonslayer's Axe",
                "Fume Ultra Greatsword",
                "Giant Stone Axe",
                "Great Machete",
                "Greatshield of Artorias",
                "Greatsword of Artorias",
                "Melinda's Greataxe",
                "Obsidian Greatsword",
                "Pursuer's Greatshield",
                "Shield Crossbow",
                "Silver Knight Straight Sword",
                "Spitfire Spear",
                "Warpick",
                "Zweihander",
            ]
        },
        2: {
            1: [
                "Black Iron Armour",
                "Black Iron Armour (Legendary)",
                "Black Knight Armour",
                "Catarina Armour (Legendary)",
                "Drang Armour",
                "Exile Armour",
                "Old Ironclad Armour",
                "Stone Knight Armour",
                "Sunless Armour",
                "Worker Armour",
                "Alonne Greatbow",
                "Bloodshield",
                "Bonewheel Shield",
                "Caestus",
                "Crescent Axe",
                "Dragon Crest Shield",
                "Dragonslayer Greatbow",
                "Effigy Shield",
                "Exile Greatsword",
                "Four-Pronged Plow",
                "Great Scythe",
                "Great Wooden Hammer",
                "Greataxe",
                "Lothric Knight Greatsword",
                "Morion Blade",
                "Pierce Shield",
                "Pike",
                "Porcine Shield",
                "Reinforced Club",
                "Silver Knight Shield",
                "Spiked Mace",
                "Stone Greataxe",
                "Stone Greatshield",
                "Stone Greatsword",
                "Thrall Axe",
                "Battle Axe",
                "Northern Armour",
                "Round Shield",
            ],
            2: [
                "Black Iron Armour (Legendary)",
                "Black Knight Armour (Legendary)",
                "Catarina Armour (Legendary)",
                "Old Ironclad Armour",
                "Paladin Armour",
                "Silver Knight Armour",
                "Bloodshield",
                "Claymore",
                "Great Scythe",
                "Greataxe",
                "Lothric Knight Greatsword",
                "Melinda's Greataxe",
                "Morion Blade",
                "Silver Knight Shield",
                "Silver Knight Straight Sword",
                "Spiked Mace",
                "Stone Greataxe",
                "Stone Greatshield",
                "Zweihander",
            ],
            3: [
                "Silver Knight Armour",
                "Smelter Demon Armour",
                "Steel Armour",
                "Balder Side Sword",
                "Claymore",
                "Dark Sword",
                "Dragon King Greataxe",
                "Dragon Tooth",
                "Dragonslayer Spear",
                "Dragonslayer's Axe",
                "Fume Ultra Greatsword",
                "Giant Stone Axe",
                "Great Machete",
                "Greatshield of Artorias",
                "Greatsword of Artorias",
                "Melinda's Greataxe",
                "Obsidian Greatsword",
                "Pursuer's Greatshield",
                "Shield Crossbow",
                "Silver Knight Straight Sword",
                "Spitfire Spear",
                "Warpick",
                "Zweihander",
            ]
        },
        3: {
            1: [
                "Black Iron Armour",
                "Black Iron Armour (Legendary)",
                "Black Knight Armour",
                "Drang Armour",
                "Exile Armour",
                "Stone Knight Armour",
                "Sunless Armour",
                "Worker Armour",
                "Alonne Greatbow",
                "Bonewheel Shield",
                "Caestus",
                "Crescent Axe",
                "Dragon Crest Shield",
                "Dragonslayer Greatbow",
                "Effigy Shield",
                "Exile Greatsword",
                "Four-Pronged Plow",
                "Great Scythe",
                "Great Wooden Hammer",
                "Greataxe",
                "Lothric Knight Greatsword",
                "Morion Blade",
                "Pierce Shield",
                "Pike",
                "Porcine Shield",
                "Reinforced Club",
                "Silver Knight Shield",
                "Spiked Mace",
                "Stone Greatsword",
                "Thrall Axe",
                "Battle Axe",
                "Northern Armour",
                "Round Shield",
            ],
            2: [
                "Black Iron Armour (Legendary)",
                "Black Knight Armour (Legendary)",
                "Catarina Armour (Legendary)",
                "Old Ironclad Armour",
                "Paladin Armour",
                "Silver Knight Armour",
                "Bloodshield",
                "Claymore",
                "Great Scythe",
                "Greataxe",
                "Lothric Knight Greatsword",
                "Melinda's Greataxe",
                "Morion Blade",
                "Silver Knight Shield",
                "Silver Knight Straight Sword",
                "Spiked Mace",
                "Stone Greataxe",
                "Stone Greatshield",
                "Zweihander",
            ],
            3: [
                "Silver Knight Armour",
                "Smelter Demon Armour",
                "Steel Armour",
                "Balder Side Sword",
                "Claymore",
                "Dark Sword",
                "Dragon King Greataxe",
                "Dragon Tooth",
                "Dragonslayer Spear",
                "Dragonslayer's Axe",
                "Fume Ultra Greatsword",
                "Giant Stone Axe",
                "Great Machete",
                "Greatshield of Artorias",
                "Greatsword of Artorias",
                "Melinda's Greataxe",
                "Obsidian Greatsword",
                "Pursuer's Greatshield",
                "Shield Crossbow",
                "Silver Knight Straight Sword",
                "Spitfire Spear",
                "Warpick",
                "Zweihander",
            ]
        },
        4: {
            1: [
                "Black Iron Armour",
                "Drang Armour",
                "Sunless Armour",
                "Caestus",
                "Effigy Shield",
                "Pierce Shield",
                "Reinforced Club",
                "Thrall Axe",
                "Battle Axe",
                "Northern Armour",
                "Round Shield",
            ],
            2: [
                "Black Iron Armour (Legendary)",
                "Catarina Armour (Legendary)",
                "Old Ironclad Armour",
                "Great Scythe",
                "Greataxe",
                "Lothric Knight Greatsword",
                "Morion Blade",
                "Silver Knight Shield",
                "Spiked Mace",
                "Stone Greataxe",
                "Stone Greatshield",
            ],
            3: [
                "Silver Knight Armour",
                "Smelter Demon Armour",
                "Steel Armour",
                "Balder Side Sword",
                "Claymore",
                "Dark Sword",
                "Dragon Tooth",
                "Dragonslayer Spear",
                "Dragonslayer's Axe",
                "Giant Stone Axe",
                "Greatshield of Artorias",
                "Greatsword of Artorias",
                "Melinda's Greataxe",
                "Shield Crossbow",
                "Silver Knight Straight Sword",
                "Warpick",
                "Zweihander",
            ]
        }
    },
}