itemTier = {
    "Adventurer's Armour": 1,
    "Alonne Greatbow": 1,
    "Alonne Knight Armour": 1,
    "Antiquated Robes": 1,
    "Aural Decoy": 1,
    "Black Armour": 1,
    "Black Firebombs": 1,
    "Black Hand Armour": 1,
    "Black Hand Armour (Thief)": 1,
    "Black Iron Armour": 1,
    "Blacksteel Katana": 1,
    "Bonewheel Shield": 1,
    "Brigand Axe": 1,
    "Broken Straight Sword": 1,
    "Buckler": 1,
    "Caestus": 1,
    "Catarina Armour": 1,
    "Cathedral Knight Armour": 1,
    "Claws": 1,
    "Cleric Armour": 1,
    "Composite Bow": 1,
    "Court Sorcerer Robes": 1,
    "Crescent Moon Sword": 1,
    "Crest Shield": 1,
    "Crimson Robes": 1,
    "Dark Armour": 1,
    "Deacon Robes": 1,
    "Dragon Crest Shield": 1,
    "Drang Armour": 1,
    "Dung Pie": 1,
    "Eastern Iron Shield": 1,
    "Effigy Shield": 1,
    "Embraced Armour of Favour": 1,
    "Fireball": 1,
    "Firebombs": 1,
    "Firelink Armour": 1,
    "Force": 1,
    "Gold-Hemmed Black Robes": 1,
    "Great Magic Weapon": 1,
    "Heal": 1,
    "Heal Aid": 1,
    "Hollow Soldier Shield": 1,
    "Kukris": 1,
    "Longbow": 1,
    "Lothric Knight Armour": 1,
    "Mask of the Child": 1,
    "Morning Star": 1,
    "Phoenix Parma Shield": 1,
    "Pierce Shield": 1,
    "Poison Mist": 1,
    "Poison Throwing Knives": 1,
    "Porcine Shield": 1,
    "Red and White Round Shield": 1,
    "Replenishment": 1,
    "Rotten Ghru Dagger": 1,
    "Rotten Ghru Spear": 1,
    "Scimitar": 1,
    "Shortsword": 1,
    "Silver Eagle Kite Shield": 1,
    "Skull Lantern": 1,
    "Soul Arrow": 1,
    "Soulstream": 1,
    "Sunless Armour": 1,
    "Sunset Shield": 1,
    "Thrall Axe": 1,
    "Torch": 1,
    "Worker Armour": 1,
    "Archdeacon Robe": 2,
    "Black Bow of Pharis": 2,
    "Black Knight Armour": 2,
    "Black Knight Greataxe": 2,
    "Black Knight Sword": 2,
    "Bountiful Light": 2,
    "Carthus Curved Greatsword": 2,
    "Cornyx's Robes": 2,
    "Crescent Axe": 2,
    "Crystal Shield": 2,
    "Dragonrider Bow": 2,
    "Dragonscale Armour": 2,
    "Dragonslayer Greatbow": 2,
    "East-West Shield": 2,
    "Elite Knight Armour": 2,
    "Exile Armour": 2,
    "Exile Greatsword": 2,
    "Fire Surge": 2,
    "Flamberge": 2,
    "Four-Pronged Plow": 2,
    "Golden Ritual Spear": 2,
    "Great Club": 2,
    "Great Combustion": 2,
    "Great Heal": 2,
    "Great Mace": 2,
    "Great Wooden Hammer": 2,
    "Guardian Armour": 2,
    "Halberd": 2,
    "Havel's Armour": 2,
    "Homing Crystal Soulmass": 2,
    "Lothric Knight Greatsword": 2,
    "Magic Barrier": 2,
    "Magic Shield": 2,
    "Man Serpent Hatchet": 2,
    "Mannikin Claws": 2,
    "Master's Attire": 2,
    "Med Heal": 2,
    "Morion Blade": 2,
    "Murakumo": 2,
    "Old Ironclad Armour": 2,
    "Painting Guardian Armour": 2,
    "Parrying Dagger": 2,
    "Pike": 2,
    "Rapier": 2,
    "Reinforced Club": 2,
    "Sacred Oath": 2,
    "Santier's Spear": 2,
    "Small Leather Shield": 2,
    "Sorcerer's Staff": 2,
    "Soul Spear": 2,
    "Spider Shield": 2,
    "Stone Greataxe": 2,
    "Stone Greatshield": 2,
    "Stone Greatsword": 2,
    "Stone Knight Armour": 2,
    "Stone Parma": 2,
    "Sunlight Shield": 2,
    "Sunlight Straight Sword": 2,
    "Sunset Armour": 2,
    "Thorolund Talisman": 2,
    "Uchigatana": 2,
    "Velka's Rapier": 2,
    "Warden Twinblades": 2,
    "Winged Spear": 2,
    "Witch's Locks": 2,
    "Xanthous Robes": 2,
    "Alonne Captain Armour": 3,
    "Alva Armour": 3,
    "Atonement": 3,
    "Avelyn": 3,
    "Balder Side Sword": 3,
    "Black Iron Greatshield": 3,
    "Black Knight Shield (Deprived)": 3,
    "Black Leather Armour": 3,
    "Bloodshield": 3,
    "Bountiful Sunlight": 3,
    "Brass Armour": 3,
    "Broadsword": 3,
    "Carthus Curved Sword": 3,
    "Claymore": 3,
    "Cleric's Candlestick": 3,
    "Crystal Hail": 3,
    "Crystal Straight Sword": 3,
    "Dark Sword": 3,
    "Dragon Tooth": 3,
    "Dragonslayer's Axe": 3,
    "Drake Sword": 3,
    "Drang Hammers": 3,
    "Eastern Armour": 3,
    "Elkhorn Round Shield": 3,
    "Falchion": 3,
    "Fallen Knight Armour": 3,
    "Faraam Armour": 3,
    "Fire Whip": 3,
    "Fume Ultra Greatsword": 3,
    "Giant's Halberd": 3,
    "Golden Wing Crest Shield": 3,
    "Gotthard Twinswords": 3,
    "Grass Crest Shield": 3,
    "Great Chaos Fireball": 3,
    "Great Machete": 3,
    "Great Scythe": 3,
    "Greataxe": 3,
    "Hard Leather Armour": 3,
    "Havel's Greatshield": 3,
    "Hawkwood's Shield": 3,
    "Hunter Armour": 3,
    "Immolation Tinder": 3,
    "Large Leather Shield": 3,
    "Lothric's Holy Sword": 3,
    "Lucerne": 3,
    "Mirrah Armour": 3,
    "Moonlight Greatsword": 3,
    "Morne's Great Hammer": 3,
    "Onikiri and Ubadachi": 3,
    "Painting Guardian's Curved Sword": 3,
    "Paladin Armour": 3,
    "Partizan": 3,
    "Royal Dirk": 3,
    "Saint Bident": 3,
    "Shadow Armour": 3,
    "Shotel": 3,
    "Silver Knight Armour": 3,
    "Silver Knight Shield": 3,
    "Silver Knight Spear": 3,
    "Silver Knight Straight Sword": 3,
    "Soul Greatsword": 3,
    "Spiked Mace": 3,
    "Spotted Whip": 3,
    "Twin Dragon Greatshield": 3,
    "Umbral Dagger": 3,
    "Warpick": 3,
    "Washing Pole": 3,
    "Zweihander": 3
}