itemTier = {
    "Abyss Greatsword": 3,
    "Adventurer's Armour": 2,
    "Adventurer's Armour (Legendary)": 3,
    "Aged Smelter Sword": 3,
    "Alonne Armour": 3,
    "Alonne Captain Armour": 3,
    "Alonne Greatbow": 1,
    "Alonne Knight Armour": 1,
    "Alva Armour": 3,
    "Antiquated Robes": 1,
    "Archdeacon Robe": 2,
    "Armour of Thorns": 3,
    "Atonement": 3,
    "Aural Decoy": 1,
    "Avelyn": 3,
    "Balder Side Sword": 3,
    "Bellowing Dragoncrest Ring": 3,
    "Bequeathed Lord Soul": 3,
    "Bewitched Alonne Sword": 3,
    "Big Pilgrim's Key": 3,
    "Binoculars": 2,
    "Black Armour": 1,
    "Black Bow of Pharis": 2,
    "Black Firebombs": 1,
    "Black Hand Armour (Thief)": 1,
    "Black Hand Armour (common)": 1,
    "Black Iron Armour": 1,
    "Black Iron Armour (Legendary)": 3,
    "Black Iron Greatshield": 3,
    "Black Knight Armour": 2,
    "Black Knight Armour (Legendary)": 3,
    "Black Knight Greataxe": 2,
    "Black Knight Halberd": 3,
    "Black Knight Shield": 3,
    "Black Knight Shield (Black Knight)": 3,
    "Black Knight Sword": 2,
    "Black Leather Armour": 3,
    "Blacksteel Katana": 1,
    "Blessed Gem": 2,
    "Blighttown Key": 3,
    "Blinding Bolt": 3,
    "Blood Gem": 1,
    "Bloodshield": 3,
    "Blue Tearstone Ring": 3,
    "Blue Titanite": 3,
    "Bonewheel Shield": 1,
    "Bountiful Light": 2,
    "Bountiful Sunlight": 3,
    "Brass Armour": 2,
    "Brigand Axe": 1,
    "Broadsword": 3,
    "Broken Straight Sword": 1,
    "Buckler": 1,
    "Butcher Knife": 3,
    "Caestus": 1,
    "Calamity Ring": 3,
    "Carthus Curved Greatsword": 2,
    "Carthus Curved Sword": 3,
    "Carthus Flame Arc": 2,
    "Carthus Milkring": 3,
    "Catarina Armour": 1,
    "Catarina Armour (Legendary)": 2,
    "Cathedral Knight Armour": 2,
    "Chariot Lance": 3,
    "Chester's Set": 3,
    "Chloranthy Ring": 3,
    "Claws": 1,
    "Claymore": 3,
    "Clear Bluestone Ring": 3,
    "Cleric Armour": 1,
    "Cleric's Candlestick": 3,
    "Composite Bow": 1,
    "Cornyx's Robes": 2,
    "Court Sorcerer Robes": 1,
    "Covetous Gold Serpent Ring": 3,
    "Covetous Silver Serpent Ring": 3,
    "Crescent Moon Sword": 1,
    "Crescent Axe": 2,
    "Crest Shield": 1,
    "Crimson Robes": 1,
    "Crimson Robes (Legendary)": 3,
    "Crystal Gem": 2,
    "Crystal Hail": 3,
    "Crystal Magic Weapon": 2,
    "Crystal Shield": 2,
    "Crystal Straight Sword": 3,
    "Cursed Greatsword of Artorias": 3,
    "Dancer Armour": 3,
    "Dancer's Enchanted Swords": 3,
    "Dark Armour": 1,
    "Dark Armour (Legendary)": 3,
    "Dark Silver Tracer": 3,
    "Dark Sword": 3,
    "Dark Wood Grain Ring": 2,
    "Deacon Robes": 1,
    "Demon Titanite": 1,
    "Demon's Great Hammer": 3,
    "Divine Blessing": 1,
    "Drake Sword": 3,
    "Drakewing Ultra Greatsword": 3,
    "Dragon Crest Shield": 1,
    "Dragon King Greataxe": 3,
    "Dragon Scale": 1,
    "Dragon Tooth": 3,
    "Dragonrider Bow": 2,
    "Dragonscale Armour": 2,
    "Dragonslayer Armour": 3,
    "Dragonslayer Greatbow": 2,
    "Dragonslayer Spear": 3,
    "Dragonslayer's Axe": 3,
    "Drang Armour": 1,
    "Drang Hammers": 3,
    "Dung Pie": 1,
    "Dusk Crown Ring": 2,
    "East-West Shield": 2,
    "Eastern Armour": 3,
    "Eastern Iron Shield": 1,
    "Effigy Shield": 1,
    "Elite Knight Armour": 2,
    "Elkhorn Round Shield": 3,
    "Embraced Armour of Favour": 1,
    "Embraced Armour of Favour (Legendary)": 3,
    "Exile Armour": 2,
    "Exile Greatsword": 2,
    "Falchion": 3,
    "Fallen Knight Armour": 3,
    "Faraam Armour": 2,
    "Faron Flashsword": 3,
    "Fire Surge": 2,
    "Fire Whip": 3,
    "Fireball": 1,
    "Firebombs": 1,
    "Firelink Armour": 1,
    "Flamberge": 2,
    "Force": 1,
    "Four Kings Sword": 3,
    "Four-Pronged Plow": 2,
    "Fume Ultra Greatsword": 3,
    "Gargoyle Tail Axe": 3,
    "Gargoyle's Halberd": 3,
    "Gargoyle's Shield": 3,
    "Giant's Halberd": 3,
    "Giant Stone Axe": 3,
    "Gold Tracer": 3,
    "Gold-Hemmed Black Robes": 1,
    "Gold-Hemmed Black Robes (Legendary)": 3,
    "Golden Ritual Spear": 2,
    "Golden Wing Crest Shield": 3,
    "Gotthard Twinswords": 3,
    "Grass Crest Shield": 3,
    "Gravelord Sword": 3,
    "Gravelord Sword Dance": 3,
    "Great Chaos Fireball": 3,
    "Great Club": 2,
    "Great Combustion": 2,
    "Great Heal": 2,
    "Great Mace": 2,
    "Great Machete": 3,
    "Great Magic Weapon": 1,
    "Great Scythe": 3,
    "Great Swamp Ring": 1,
    "Great Wooden Hammer": 2,
    "Greataxe": 3,
    "Greatshield of Artorias": 3,
    "Greatsword": 3,
    "Greatsword of Artorias": 3,
    "Guardian Armour": 2,
    "Guardian Armour (Legendary)": 3,
    "Halberd": 2,
    "Hard Leather Armour": 3,
    "Havel's Armour": 2,
    "Havel's Armour (Legendary)": 3,
    "Havel's Greatshield": 3,
    "Hawkwood's Shield": 3,
    "Heal": 1,
    "Heal Aid": 1,
    "Heavy Gem": 2,
    "Hollow Gem": 1,
    "Hollow Soldier Shield": 1,
    "Homeward Bone": 3,
    "Homing Crystal Soulmass": 2,
    "Hornet Ring": 2,
    "Hunter Armour": 3,
    "Immolation Tinder": 3,
    "Irithyll Straight Sword": 3,
    "Irithyll Rapier": 3,
    "Iron King Hammer": 3,
    "Knight Slayer's Ring": 2,
    "Kukris": 1,
    "Large Leather Shield": 3,
    "Life Ring": 3,
    "Lifehunt Scythe": 3,
    "Lightning Gem": 1,
    "Longbow": 1,
    "Lothric Knight Armour": 1,
    "Lothric Knight Greatsword": 2,
    "Lothric's Holy Sword": 3,
    "Lucerne": 3,
    "Magic Barrier": 1,
    "Magic Shield": 2,
    "Magic Stoneplate Ring": 3,
    "Man Serpent Hatchet": 2,
    "Mannikin Claws": 2,
    "Manus Catalyst": 3,
    "Mask of the Child": 1,
    "Master's Attire": 2,
    "Med Heal": 2,
    "Melinda's Greataxe": 3,
    "Minotaur Helmet": 3,
    "Mirrah Armour": 3,
    "Mon Ring": 3,
    "Moonlight Greatsword": 3,
    "Morion Blade": 2,
    "Morne's Great Hammer": 3,
    "Morning Star": 1,
    "Murakumo": 2,
    "Notched Whip": 2,
    "Obscuring Ring": 3,
    "Obsidian Greatsword": 3,
    "Old Dragonslayer Spear": 3,
    "Old Ironclad Armour": 2,
    "Old Leo Ring": 3,
    "Onikiri And Ubadachi": 3,
    "Outrider Armour": 3,
    "Painting Guardian Armour": 2,
    "Painting Guardian Curved Sword": 3,
    "Paladin Armour": 3,
    "Parrying Dagger": 3,
    "Partizan": 3,
    "Phoenix Parma Shield": 1,
    "Pierce Shield": 1,
    "Pike": 2,
    "Poison Gem": 1,
    "Poison Mist": 1,
    "Poison Throwing Knives": 1,
    "Pontiff's Left Eye": 3,
    "Porcine Shield": 1,
    "Priscilla's Dagger": 3,
    "Pursuer's Greatshield": 3,
    "Pursuer's Ultra Greatsword": 3,
    "Pursuers": 3,
    "Rapier": 2,
    "Rapport": 2,
    "Raw Gem": 1,
    "Red and White Round Shield": 1,
    "Red Tearstone Ring": 1,
    "Reinforced Club": 1,
    "Replenishment": 1,
    "Ring of Blades": 3,
    "Ring of Favour": 2,
    "Rotten Ghru Dagger": 1,
    "Rotten Ghru Spear": 1,
    "Royal Dirk": 3,
    "Royal Swordsman Armour": 2,
    "Sacred Oath": 2,
    "Saint Bident": 3,
    "Sanctum Priestess Tiara": 3,
    "Sanctus": 3,
    "Santier's Spear": 3,
    "Scimitar": 1,
    "Shadow Armour": 3,
    "Sharp Gem": 2,
    "Shield Crossbow": 3,
    "Shortsword": 1,
    "Shotel": 3,
    "Silver Eagle Kite Shield": 1,
    "Silver Knight Armour": 3,
    "Silver Knight Shield": 3,
    "Silver Knight Spear": 3,
    "Silver Knight Straight Sword": 3,
    "Simple Gem": 1,
    "Skull Lantern": 1,
    "Small Leather Shield": 2,
    "Smelter Demon Armour": 3,
    "Smelter Sword": 3,
    "Smough's Armour": 3,
    "Smough's Hammer": 3,
    "Soldier Key": 3,
    "Soothing Sunlight": 3,
    "Sorcerer's Staff": 2,
    "Soul Arrow": 1,
    "Soul Greatsword": 3,
    "Soul Spear": 2,
    "Soulstream": 1,
    "Spider Shield": 2,
    "Spiked Mace": 3,
    "Spiked Shield": 3,
    "Spitfire Spear": 3,
    "Spotted Whip": 3,
    "Steel Armour": 3,
    "Stone Greataxe": 2,
    "Stone Greatshield": 2,
    "Stone Greatsword": 2,
    "Stone Knight Armour": 2,
    "Stone Parma": 3,
    "Sun Princess Ring": 3,
    "Sunless Armour": 1,
    "Sunlight Shield": 2,
    "Sunlight Straight Sword": 3,
    "Sunset Armour": 2,
    "Sunset Shield": 1,
    "Thorolund Talisman": 2,
    "Thrall Axe": 1,
    "Throwing Knives": 1,
    "Tiny Being's Ring": 1,
    "Titanite Catch Pole": 3,
    "Torch": 1,
    "Tower Shield": 3,
    "Twin Dragon Greatshield": 3,
    "Uchigatana": 2,
    "Umbral Dagger": 3,
    "Velka's Rapier": 2,
    "Vordt's Great Hammer": 3,
    "Warden Twinblades": 2,
    "Warpick": 3,
    "Washing Pole": 3,
    "Winged Knight Armour": 3,
    "Winged Knight Halberd": 3,
    "Winged Knight Twin Axes": 3,
    "Winged Spear": 2,
    "Witch's Locks": 2,
    "Wolf Ring": 3,
    "Worker Armour": 1,
    "Xanthous Robes": 2,
    "Zweihander": 3
}